### ISSUE TITLE
Update require phpagebuilder

### ISSUE THREAD

**Issue by alifu** [HansSchouten/Laravel-Pagebuilder#1]
HI, can you update version for phpagebuilder? because in composer.json still require v0.2.0

**Comment by HansSchouten** [comment]
Hi Alif, thanks for your feedback. I updated the composer.json

**Comment by javeedrahman** [comment]
Hi @alifu ,

Could you please help me how to install it on laravel 6.

**Comment by HansSchouten** [comment]
Hi Javeed, please follow the steps here: https://github.com/HansSchouten/Laravel-Pagebuilder#installation
