### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Enmaboya** [HansSchouten/Laravel-Pagebuilder#10]
When trying to login to /admin, the "page not found" error appears.

Steps for playback:
1) A clean Laravel installation.
2) Installing Laravel-Pagebuilder
3) Performing items from readme.

At the first run, sometimes the /admin page opens, I enter my login and password, redirect me to /admin/auth and the "page not found" error appears.
Later on, even the /admin page shows an error.

They are used:
PHP 7.3.17
Laravel Framework 6.18.14
Windows 10 / Linux Mint 19.4 / Ubuntu 18.04 (same error everywhere)
______
in the Laravel Framework 7.11.0 the problem is the same
______
After taking a little look, I found out that the problem is possible in the function phpb_in_module( ) in helpers php

some obscure values come into play.
![image](https://user-images.githubusercontent.com/32259003/81764893-a5e5a880-94e3-11ea-9fe8-4e224c61bc73.png)
![image](https://user-images.githubusercontent.com/32259003/81764938-b5fd8800-94e3-11ea-89f3-1b6fc3516a49.png)

**Comment by HansSchouten** [comment]
Hi, do you have set your APP_URL in Laravel .env correctly to `http://127.0.0.1:8000`?

**Comment by Enmaboya** [comment]
> Hi, do you have set your APP_URL in Laravel .env correctly to `http://127.0.0.1:8000`? Could you maybe further output the content of `phpb_current_relative_url()` or how it came to this `/n` value?

seems to have solved the problem.
It's in the url.
for some reason, 127.0.0.1:8000 didn't work.
 set the domain name and the problem disappeared.

But the only question left is, how do you connect other elements besides "Header"?
![image](https://user-images.githubusercontent.com/32259003/82003027-67312900-9670-11ea-863f-be9a28903119.png)

**Comment by HansSchouten** [comment]
Ok good to hear that it is working now. About creating blocks, please see this discussion over here: https://github.com/HansSchouten/Laravel-Pagebuilder/issues/8#issuecomment-625748145.
