### ISSUE TITLE
Urls of the created pages are not showing up, so i cannot view or preview the pages

### ISSUE THREAD

**Issue by estelle-zeuk** [HansSchouten/Laravel-Pagebuilder#100]
![image](https://user-images.githubusercontent.com/77698664/124096001-189c4500-da52-11eb-9c15-f09b522f744c.png)

**Comment by estelle-zeuk** [comment]
@HansSchouten please for your help

**Comment by HansSchouten** [comment]
By default the english variant of the URLs is shown if I am correct.

**Comment by estelle-zeuk** [comment]
Nothing is shown, i cannot even preview pages when editing. I am new to laravel and php

**Comment by estelle-zeuk** [comment]
> Nothing is shown, i cannot even preview pages when editing. I am new to laravel and php

i am redirect on the welcome page of the page builder

**Comment by HansSchouten** [comment]
Can you check your database. Do the pages have records in the page_translations table, with a locale field and route set?

**Comment by estelle-zeuk** [comment]
![image](https://user-images.githubusercontent.com/77698664/124155751-bb72b480-da8e-11eb-8c70-27d65554b453.png)
yes, there is route set for every page

**Comment by estelle-zeuk** [comment]
> By default the english variant of the URLs is shown if I am correct.

That'is it!!! Thanks!
