### ISSUE TITLE
Drag and Drop wherever I want

### ISSUE THREAD

**Issue by abdullahniazi96** [HansSchouten/Laravel-Pagebuilder#101]
Is there any way to drag and drop elements where ever I want . Without auto alignment into grids.
Because its not allowing me to put 2 elements in front of each other even after i set both of their widths to 50%.

![Screenshot (14)](https://user-images.githubusercontent.com/85108041/124584620-e6358200-de6d-11eb-95f2-7147e956f5be.png)

here I want to put hello world in front of image.
Please guide

**Comment by HansSchouten** [comment]
I think in that case it is better to build a block with an image and text and then just edit the text using the pagebuilder.
In the background [GrapesJS](https://grapesjs.com/demo.html) is being used and I think they don't support dragging elements onto eachother.

**Comment by abdullahniazi96** [comment]
Okay.
Thanks for the quick response.

**Comment by abdullahniazi96** [comment]
@HansSchouten 
Can you send me few (more complex blocks) that you made.

**Comment by abdullahniazi96** [comment]
@HansSchouten
Can you send me few (more complex blocks) that you made.
Because I am having issue in creating ones. 
I'll be able to use your examples to have better understanding and make my own. Specially their settings.

**Comment by HansSchouten** [comment]
This is an example of a block to add a custom piece of HTML:

`blocks/html/config.php`
```php
<?php

return [
    "title" => "HTML",
    "settings" => [
        "html" => [
            "type" => "text",
            "label" => "HTML"
        ]
    ]
];
```

`blocks/html/view.php`
```php
<?php
if (phpb_in_editmode()):
    echo "<h4>This block adds custom html to the page.</h4>";
else:
?>
<?= $block->setting('html', true) ?>
<?php
endif;
?>
```
---

This is an example block to add a custom select form element:
`blocks/form-select/config.php`
```php
<?php

return [
    "category" => "Form components",
    "title" => "Form select element",
    "settings" => [
        "label" => [
            "type" => "text",
            "label" => "Label",
            "value" => "Example label",
        ],
        "options" => [
            "type" => "text",
            "label" => "Options (provide comma separated options)",
            "value" => "option 1, option 2",
        ],
        "required" => [
            "type" => "yes_no",
            "label" => "This selector is required",
            "value" => "0",
        ],
    ]
];
```

`blocks/form-select/view.php`
```php
<?php
$id = 'ID_' . Illuminate\Support\Str::random(20);
$name = Illuminate\Support\Str::slug($block->setting('label'));

$errors = Session::get('errors', new Illuminate\Support\MessageBag);
?>
<div class="form-group">
    <label for="<?= $id ?>" class="form-label <?= $block->setting('required') ? 'required' : '' ?>">
        <?= $block->setting('label') ?>
    </label>

    <input type="hidden" name="<?= $name ?>[label]" value="<?= $block->setting('label') ?>">
    <input type="text" name="<?= $name ?>[value]" id="<?= $id ?>" <?= $block->setting('required') ? 'required="required"' : '' ?> class="form-control <?= $errors->has($name) ? 'has-error' : '' ?>" value="<?= e(old($name)['value'] ?? null) ?>">

    <?php
    if ($errors->has($name)):
    ?>
    <span class="help-block">
        <strong><?= e($errors->first($name)) ?></strong>
    </span>
    <?php
    endif;
    ?>
</div>
```

**Comment by abdullahniazi96** [comment]
Thank you very much.
This will be really helpful for me.
