### ISSUE TITLE
ON clicking view 

### ISSUE THREAD

**Issue by abdullahniazi96** [HansSchouten/Laravel-Pagebuilder#102]
Blank white page appears.
Kindly need guidance on this

**Comment by HansSchouten** [comment]
Can you be more specific, clicking where?

**Comment by abdullahniazi96** [comment]
Sorry for not mentioning properly and for bothering you again and again as I am quiet new to this.

![Screenshot (15)](https://user-images.githubusercontent.com/85108041/124701716-7cb68180-df08-11eb-8de4-bde81c1504b9.png)
![Screenshot (18)](https://user-images.githubusercontent.com/85108041/124701747-893ada00-df08-11eb-929e-0eb5411cbcaf.png)
when I click on these view buttons.

Instead of giving the preview of my designed page it gives blank white page.
**Like this**
![Screenshot (16)](https://user-images.githubusercontent.com/85108041/124701901-d1f29300-df08-11eb-886f-61b66031e052.png)

**Comment by HansSchouten** [comment]
The URL you store should be /ozonedhome and not the full URL.

**Comment by abdullahniazi96** [comment]
Done!
Thanks man much obliged.
Can yo please also suggest me a package to export designed page screen to a PDF.

**Comment by HansSchouten** [comment]
You're welcome.
Have a look at html2canvas, to create an image of a webpage which you could then convert to PDF.
Or maybe [mPDF](https://github.com/mpdf/mpdf) will help.
It will however be difficult to get all styling correctly applied, but these options should give an initial solution.

**Comment by abdullahniazi96** [comment]
OK thanks man.
