### ISSUE TITLE
Draggable Div 

### ISSUE THREAD

**Issue by abdullahniazi96** [HansSchouten/Laravel-Pagebuilder#104]
Is there any to apply this feature [Draggable Block](http://plnkr.co/edit/ZwiDo9gx5nAcz4Z0daTo?p=preview&preview) on this package.
I tried to the best of my knowledge but didn't work.

If we can embed this feature into this it will be an amazing addition

This chunk of [code](http://plnkr.co/edit/3rCPJF?preview) is even allowing the divs to be dragged on to on another.

Is there a way to create a block with this property.

**Comment by abdullahniazi96** [comment]
I we can embed this feature into this it will be an amazing addition

**Comment by HansSchouten** [comment]
Hi, thanks for the suggestion but at the moment I unfortunately don't have the time to add support for that.
Also responsiveness would be a challenge with blocks that have a fixed x,y coordinate. It is difficult to decide what to do on different breakpoints.

**Comment by abdullahniazi96** [comment]
OK
