### ISSUE TITLE
page builder design

### ISSUE THREAD

**Issue by kurt1027** [HansSchouten/Laravel-Pagebuilder#105]
Hi sir @HansSchouten I followed everystep on integrating the pagebuilder in an existing projectbut after setting it up I'd be able to launch the page builder but the UI is kinda disoriented and upon checking console logs I've seen some grapejs plugin errors 
Page Builder:
![image](https://user-images.githubusercontent.com/49175876/127665839-02e174d1-92e8-4727-a08c-696bcaaf3b40.png)

Console Log:
![image](https://user-images.githubusercontent.com/49175876/127665950-f7d9c477-5c52-492f-9b4a-b93aabb03911.png)

your response means a lot thank you in advance :)

**Comment by HansSchouten** [comment]
It might go wrong when using a port number in the URL. Please check your .env file to see whether the APP_URL is correct.

**Comment by kurt1027** [comment]
Hi sir @HansSchouten  I finally get the chance to display the page builder loader(which is a good sign I'm not getting that last time) after fixing the base url but It just keep on loading any thoughts about this one? I think I'm one step away haha
