### ISSUE TITLE
Pagebuilder Purchase

### ISSUE THREAD

**Issue by chirag123456** [HansSchouten/Laravel-Pagebuilder#11]
Hello

I want to purchase pagebuilder with theme and need all functionality for drag and drop please guide me for purchase theme which i have to buy for get all  drag and drop functionality.

and please let me know after purchase theme what to make change in my project so i can use your library in my project for Create Dynamic pages with drag and drop functionality.

**Comment by HansSchouten** [comment]
Hi, you do not need to purchase the pagebuilder, it is free for anyone to use. However, it is not a tool to give you a fully functioning website out of the box. For that, Wix or similar systems are perfect. This tool helps programmers build websites with custom components that they want customers to manage using a simple drag & drop pagebuilder. Therefore, the project (currently) does not come with a complete set of blocks, you need to create these yourself.

However, creating your own blocks is very easy. Each block has just a simple .html or a .php file and that's it. So it just a matter of tearing an awesome [HTML5 theme](https://themeforest.net/category/site-templates?sort=sales&tags=html5#content) apart into small snipets (i.e. blocks) and you're done. So you can use any html/css theme you find online (paid or for free). You just need to split it into blocks.

That being said, I understand it is not always pleasant to do this for a quick and simple website, so I am planning to create a default theme based on bootstrap that has blocks for each bootstrap component.

**Comment by b4oshany** [comment]
Can you do a youtube video about setting it up and using it?

**Comment by HansSchouten** [comment]
Maybe in the future, but at the moment I do not have time for it. For now the few steps in the readme and the example block contain the basics.
