### ISSUE TITLE
Doesn't not working in production server.

### ISSUE THREAD

**Issue by andresu22** [HansSchouten/Laravel-Pagebuilder#111]
Hi, @HansSchouten 

I'm using Laravel-Page Builder in my project, in localhost is working ok, but when I upload in the server the page builder is not working anymore.

When I try to edit the page is stuck loading with this message: 'Loading pagebuilder..'

And the public page load without styles, totally broken.

The console is not showing any error.

![image](https://user-images.githubusercontent.com/30181542/134067489-861fae5d-ba02-4c64-9a95-134d73a56c0e.png)

public page without styles -> 
![image](https://user-images.githubusercontent.com/30181542/134067612-6b7810e4-3ed3-4642-ae9e-369264554742.png)

I appreciate if anyone know or can give any idea about this.

Thank you

**Comment by akies1** [comment]
how did you solved the problem.
