### ISSUE TITLE
Grapes tags not showing 

### ISSUE THREAD

**Issue by sadiqueali786** [HansSchouten/Laravel-Pagebuilder#129]
I am trying to add tags to the page build and can't do so.

![image](https://user-images.githubusercontent.com/60964121/179346488-17eac8e2-1e7f-4617-9893-d9ffb835a84a.png)

Please help

**Comment by HansSchouten** [comment]
With this package you need to buy/find/create a regular HTML5 theme and cut it into smaller pieces (blocks) yourself
