### ISSUE TITLE
assets are not loaded

### ISSUE THREAD

**Issue by Dontorpedo** [HansSchouten/Laravel-Pagebuilder#13]
hi again,

apparently css and other assets inside a theme are not loaded, also not in the demo.. 

` <link href="<?= phpb_theme_asset('css/main.css') ?>" rel="stylesheet">`

i cant also reach the file in browser..

tried like: domain.com/themes/demo/css/style.css and domain.com/themes/demo/public/css/style.css

i tried also to use the htaccess from your boilerplate, but no success :(

thanks

**Comment by HansSchouten** [comment]
Hi, I just checked and you are correct. The theme assets are not yet symlinked from the `public` folder to the current theme folder. To fix this I updated the commands for publishing a theme. To fix your environment you can update to the latest release and run: `php artisan pagebuilder:publish-theme [theme-name]`.

**Comment by b4oshany** [comment]
This is still failing for me...

**Comment by HansSchouten** [comment]
After running the command, do you see a symlink from /public/themes/[your theme name]? Which points to the public folder of your theme. Your theme should have a public folder in which you create for example a folder `assets` or `images`.

**Comment by Dontorpedo** [comment]
Didn't work for me neither, had to uninstall and install again to make it work.. maybe bc you didn't change the version?
