### ISSUE TITLE
More Menu items on CKE Editor

### ISSUE THREAD

**Issue by taobad** [HansSchouten/Laravel-Pagebuilder#134]
Hello All, 
   Is there a place where i can edit the settings of the CKE Editor so i can more menu to support formatting text. Example is say i want a bullet list menu on it. currently i only have this options. How would i enable it please? Thanks.

<img width="1738" alt="image" src="https://user-images.githubusercontent.com/8578593/188423655-c1a792f4-643e-4d1e-8cff-b97ad86ec711.png">

**Comment by HansSchouten** [comment]
For now this is not supported, but you can create an unordered list block (that simply contains a `<ul><li>example</li></ul>`) and drag it onto the page. Next you can add and edit list items.

**Comment by taobad** [comment]
Ah noted. Thank you for the quick response.

**Comment by taobad** [comment]
Works like a charm. Thanks.
