### ISSUE TITLE
Can you provide an example of using use_website_manager=false.

### ISSUE THREAD

**Issue by b4oshany** [HansSchouten/Laravel-Pagebuilder#14]
Based on the document of PHPageBuilder to use an already existing login feature, I would need to implement my phone create/editing/remove functions:

> Disable the module
Do you already have admin login functionality in your project? Then you can disable the website manager module by setting use_website_manager to false in your config. Next, you use or implement the page create/edit/remove functionality in your project and then directly launch the pagebuilder. You can render the pagebuilder from your project by using the PHPageBuilder\Modules\GrapesJS\PageBuilder class.

However, I'm not sure what to do.  I tried to do. I was thinking of doing the following:

```
Route::any(
    '/pagebuilder/create', 'Backend\PageBuilder@create')->name(
        'page.builder.create');
```

Afterwards, I would set the permission for the pagebuilder.

However, this didn't work.

**Comment by HansSchouten** [comment]
Which part of this snippet is not working? You should then implement controller actions for a number of these routes with your own functionality that adds/updates and removes pages from the pages database table.

**Comment by Dontorpedo** [comment]
i have set use_website_manager=false, use_router=false, but kept use_login=true and changed the class to my own.. this way i was able to use the pagebuilder inside my existing app.. maybe this helps you.
