### ISSUE TITLE
Can't run php artisan migrate

### ISSUE THREAD

**Issue by akies1** [HansSchouten/Laravel-Pagebuilder#142]
Hi, When I want run php artisan migrate, I've got this error:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.pagebuilder__settings' doesn't exist

How I can fix this?

thanks a lot

**Comment by AboutErfan** [comment]
Hey,I had the same problem, [check this link](https://github.com/HansSchouten/Laravel-Pagebuilder/issues/141)

**Comment by akies1** [comment]
still I am facing same issue.

**Comment by akies1** [comment]
``
