### ISSUE TITLE
li tag is beeing removed

### ISSUE THREAD

**Issue by Dontorpedo** [HansSchouten/Laravel-Pagebuilder#15]
hi again,

1) i added some blocks to the builder (header, footer and so on) and saw a strange behaviour, when i click on a li element in the header, the li is removed and the design broken.. see in the video.
what can i do about this?

https://share.getcloudapp.com/P8uemELl

2) Background image which is set in css or inline, is not shown.. and the element can't be editet.. like the hero seen in my video.. i cant edit the text inside..

3)some suggestions:

a custom css/js panel would be great, also the possibility to save ready templates for reuse (not the same as blocks).. how would one do this?

regards

**Comment by HansSchouten** [comment]
Hi, I thanks for the feedback. I have to look into editing (un)ordered lists, I think it is because they are not editable as a whole or CKEditor changes it into a paragraph tag or something. What I do is I have in my laravel project a simple menu builder (for example with [nestable](https://github.com/RamonSmit/Nestable2)). Then, I use a .php block that loads all items of the menu stored in the database.

As you can see in this image, it should be possible to edit a css background image.
![afbeelding](https://user-images.githubusercontent.com/5946444/85168378-9556e980-b26a-11ea-9395-e560672a3415.png)

I think you mean creating custom layouts (like the master layout) and then add some default blocks. That is indeed very helpful. I have it in my platform that integrates the pagebuilder, so it certainly is already possible to build this on top of the pagebuilder.

I have a separate `page_layouts` table that has the same structure as the `pages` table. This is the controller action that I am using:
```
public function buildLayout($pageLayoutId = null)
{
	$route = $_GET['route'] ?? null;
	$action = $_GET['action'] ?? null;

	// override settings to use the pagebuilder on layouts instead of pages
	config([
		'pagebuilder.pagebuilder.url' => '/admin/website/page-layouts/build',
		'pagebuilder.pagebuilder.actions.back' => '/admin/website/page-layouts',
		'pagebuilder.page.class' => \PHPageBuilder\Page::class,
		'pagebuilder.page.translation.class' => \PHPageBuilder\PageTranslation::class,
		'pagebuilder.page.table' => 'page_layouts',
	]);

	// refresh the PhpPageBuilder singleton with the updated config
	app()->extend('phpPageBuilder', function ($command, $app) {
		return new PHPageBuilder(config('pagebuilder'));
	});

	// get the page layout as Page object
	$pageLayoutId = is_numeric($pageLayoutId) ? $pageLayoutId : ($_GET['page'] ?? null);
	$pageRepository = new PageRepository;
	/* @var PageContract $pageLayout */
	$pageLayout = $pageRepository->findWithId($pageLayoutId);

	/* @var PHPageBuilder $phpPageBuilder */
	$phpPageBuilder = app()->make('phpPageBuilder');
	$pageBuilder = $phpPageBuilder->getPageBuilder();

	$customScripts = view("website::pagebuilder.scripts")->render();
	$pageBuilder->customScripts('head', $customScripts);
	$pageBuilder->handleRequest($route, $action, $pageLayout);
}
```

**Comment by Dontorpedo** [comment]
nice, thank you for the code!

what i meant is, i cant edit the text inside the block which has a background image.

i found out its not possible to put a block inside a block or did i miss something?

i created some "general" blocks like column, text, button and so on and tried to put the text or button block inside the colulmn, but thats not possible :(

**Comment by HansSchouten** [comment]
In my screenshot I have a text-editable block with a background image, so it should be a problem with your specific block html structure. I just used a block with a view.html which contains a <p> tag.

You cannot just drop blocks everywhere, but you can create a blocks container in which it is possible to drop blocks. You create a blocks container by following [these steps](https://github.com/HansSchouten/PHPageBuilder#blocks-inside-blocks).

**Comment by HansSchouten** [comment]
I reproduced the problem with li tags being removed and I just committed a fix.

**Comment by billiemead** [comment]
@HansSchouten 

I am trying to integrate the layouts table as you detailed above. 

I was wondering if you could give an example of what to use inside of PageLayoutRepository and the master layout file view.php?  Also, where does the helper method findOneByField come from as Laravel 6 is giving me a hard time with it?

Cheers,
Billie

**Comment by HansSchouten** [comment]
You are correct, I see that method is part of the boilerplate I am working with, the findOneByField does this:
```php
    public function findOneByField($field, $value = null, $columns = ['*'])
    {
        $model = $this->findByField($field, $value, $columns = ['*']);
        return $model->first();
    }
```
So just a findByField with a first.

PageLayoutRepository is a simple class I use that allows an abstraction for CRUD on page layouts (with some customization for my use cases). In standard Laravel a PageLayout class extending the base eloquent Model class would also work just fine.

This is a simplified version of my current master layout:
```php
<!DOCTYPE html>
<html lang="<?= current_frontend_language() ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= e($page->getTitle()) ?></title>
    <meta name="description" content="<?= e($page->getMetaDescription()) ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="robots" content="all,follow">
    <meta name="csrf-token" content="<?= e(csrf_token()) ?>">

    <link rel="stylesheet" href="<?= themeAssetVersion('css/app.css') ?>">
</head>
<body>

[block slug="error-message"]

<?= $body ?>

<!-- JavaScript -->
<script src="<?= themeAssetVersion('js/app.js') ?>"></script>
<!-- Run block scripts -->
<script type="text/javascript">
    document.querySelectorAll("script").forEach(function(scriptTag) {
        scriptTag.dispatchEvent(new Event('run-script'));
    });
</script>
<?php
foreach ($page->get('custom-scripts-urls') ?? [] as $scriptUrl):
    echo '<script src="' . e($scriptUrl) . '"></script>';
endforeach;
?>
</body>
</html>
```

themeAssetVersion is a simple helper method I use to bust outdated cached css/js files:
```php
    /**
     * Return the theme asset path with a version GET parameter based on the latest file change.
     *
     * @param $assetPath
     * @return string
     */
    function themeAssetVersion($assetPath)
    {
        $theme = config('pagebuilder.theme.active_theme');
        $themeFolder = config('pagebuilder.theme.folder') . '/' . $theme;
        $fullAssetPath = $themeFolder . '/public/' . $assetPath;

        if (realpath($fullAssetPath)) {
            $modifiedTime = filemtime($fullAssetPath);
            return url(phpb_theme_asset($assetPath) . '?v=' . $modifiedTime);
        }
        return url(phpb_theme_asset($assetPath));
    }
```

Ignoring this method and using phpb_theme_asset intead would also work just fine.

**Comment by billiemead** [comment]
@HansSchouten 
Thank you so much. I will work on this straight away and can't wait to see how it works. Cheers Hans!

**Comment by Zeeshan-1313** [comment]
@HansSchouten can i please update CKeditor
becouse this dont have option for listi <li> builts poitns etc
