### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta_title' in 'field list'

### ISSUE THREAD

**Issue by bayron-st** [HansSchouten/Laravel-Pagebuilder#150]
When I try to create a new page, it returns the following error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta_title' in 'field list'.

Checking a bit, the migration for the "page_translations" table does not have all the columns that the creation form requires.
I solved it by manually adding the following two lines in the migration of "create_page_translations_table", schema of "page_translations"

$table->string('meta_title', 255);
$table->text('meta_description');

**Comment by EhabAmawi** [comment]
I am facing the same problem, 
this repo has a lot of issue and bugs

**Comment by HansSchouten** [comment]
@bayron-st thanks for pointing out! Fixed it in the new release.
