### ISSUE TITLE
Cannot drag & drop, white screen with nothing to do

### ISSUE THREAD

**Issue by artifex-media** [HansSchouten/Laravel-Pagebuilder#154]
Hi,

I have a fresh install of Laravel 9 and the Laravel-Pagebuilder package, running on php 8.1., with the demo theme published.
All went fine installing except when you are edit/create a page, nothing happens when I drag an element to the page (which at that point is a white screen). I can do whatever I want, nothing works. I do see some errors in the console:

![chrome_9E3AOFbrgO](https://github.com/HansSchouten/Laravel-Pagebuilder/assets/43996366/220a8c55-8613-435e-8a88-13cdf9d09249)

**Comment by HydroMoon** [comment]
@artifex-media You will need to drag & drop to the top of the page. We need to figure out how to make dropzone larger and show outline to know where the dropzone is.

**Comment by artifex-media** [comment]
> @artifex-media You will need to drag & drop to the top of the page. We need to figure out how to make dropzone larger and show outline to know where the dropzone is.

Yeah took me a while to figure that out, it was a very very very narrow space for me. 
Thanks for your reply anyway!

**Comment by clonefunnels** [comment]
How do we replace with the default GrapesJS editor instead of this not very functional one?
