### ISSUE TITLE
No publishable resources for tag [config]

### ISSUE THREAD

**Issue by humzakhaled** [HansSchouten/Laravel-Pagebuilder#156]
php artisan vendor:publish --provider="HansSchouten\LaravelPageBuilder\ServiceProvider" --tag=config
>>

   INFO  No publishable resources for tag [config].

**Comment by humzakhaled** [comment]
fixed it.

**Comment by juanjullian** [comment]
how do you fixed?

**Comment by Shaz3e** [comment]
Same here I cannot run the config publish command
php artisan vendor:publish --provider="HansSchouten\LaravelPageBuilder\ServiceProvider" --tag=config
