### ISSUE TITLE
Issue on block separation using tailwind CSS

### ISSUE THREAD

**Issue by surendharnagarajan** [HansSchouten/Laravel-Pagebuilder#157]
When I want to convert a website using tailwind CSS to a block, I face an issue.  That is when using w-1/2, it changes to w-1-2, resulting in changes to the website.  Can you tell me how to fix this?

Using Page Builder:

![using-page-builder](https://github.com/HansSchouten/Laravel-Pagebuilder/assets/40541316/5312237b-c521-4765-aa25-78455812a56b)

Actual Section:

![actual-section](https://github.com/HansSchouten/Laravel-Pagebuilder/assets/40541316/59fc9b4f-435b-4392-a944-6b0aba191d03)

**Comment by mguariero** [comment]
$pagebuilder = new PageBuilder();
$pagebuilder->customScripts('head', view('pagebuilder.custom_scripts')->render());


// pagebuilder.custom_scripts
        
<script type="text/javascript">
    const escapeName = (name) => `${name}`.trim().replace(/([^a-z0-9\w-:/\[\]]+)/gi, '-');

    window.customConfig = {
        selectorManager: {escapeName},
    };
</script>

**Comment by surendharnagarajan** [comment]
Thank you 👍 :)
