### ISSUE TITLE
Great package, please provide way to override the pagebuilder and gjs config so we can install gjs plugins easily

### ISSUE THREAD

**Issue by jay2success** [HansSchouten/Laravel-Pagebuilder#16]
Hi, Thanks for great package.

The reason we can override the pagebuilder and gjs config is so we can add our own gjs plugins easily.

For example there are 2 gjs plugins for basic elements:
https://github.com/kaoz70/grapesjs-blocks-bootstrap4
https://github.com/artf/grapesjs-preset-webpage

We can install those plugins into your pagebuilder package easily without modifying the src.
So we can add and modify the pagebuilder based on any plugins we want.

For example with "blocks bootstrap4" plugins we can add basic blocks like bs4 row, column, hero, image, etc. Which already inlined with your package cause its using bs4 as base theme.

Thanks.

**Comment by HansSchouten** [comment]
Thanks for the suggestion, I will have a look to see if we can make these gjs plugins work (since I have quite some customizations applied). But it might still just work out of the box.

**Comment by jay2success** [comment]
Hi, great, thanks a lot. 

It will be cool if there is special panel for bs4 basic elements for drag and drop.

Thanks again.

**Comment by abdulbasit92** [comment]
Hi, I have been trying to install this package on a new laravel 7 project but It's not working. It shows blank on the main page. Also if I create a new page through admin it again shows a blank page.

**Comment by HansSchouten** [comment]
Please have a look at the other issues, also [here](https://github.com/HansSchouten/PHPageBuilder) as this have been debugged for several times. Ensure you are using your environment correctly.
