### ISSUE TITLE
PDOException after updating from v0.10.0 to v0.11.0

### ISSUE THREAD

**Issue by OusManDiouf** [HansSchouten/Laravel-Pagebuilder#17]
Hi hans, I'm getting the exception bellow after updating from v0.10.0 to v0.11.0

`PDOException
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= '4'' at line 1 `

![exception](https://user-images.githubusercontent.com/24594604/85256800-0eba2c00-b465-11ea-8cd2-2b100beb1682.png)

Help would be welcome.
Thanks

**Comment by OusManDiouf** [comment]
Still getting the same issue after a fresh install of the last release.
It blows up with the following exception  when i try to add  a new page from the WebsiteManager.

`PDOException
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '='1'' at line 1 `

**Comment by HansSchouten** [comment]
Hi could you have a further look at the contents of `$parameters` and `$query`? This error is not revealing anything unfortunately.

**Comment by virgiltu** [comment]
This issues is because you are using an older version of Mysql. Please use version 6 or higher.
