### ISSUE TITLE
Style Manager - Background image upload

### ISSUE THREAD

**Issue by dsCyber** [HansSchouten/Laravel-Pagebuilder#18]
image saved as [upload_url] / [image_public_id].[extension]
but image url display as [upload_url] / [image_public_id] / [original_file_name].[extension]
any suggestions?

**Comment by HansSchouten** [comment]
You could try to overwrite the `handleFileUpload()` method of the [PageBuilder class](https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/GrapesJS/PageBuilder.php) by extending this class and using your version of the class in the `pagebuilder.class` setting in config.

**Comment by dsCyber** [comment]
it's working now.thanks.
