### ISSUE TITLE
How to make custom function to store a new page ?

### ISSUE THREAD

**Issue by kousar2334** [HansSchouten/Laravel-Pagebuilder#23]

**Comment by HansSchouten** [comment]
Here you see some example code for various customizations: https://github.com/HansSchouten/Laravel-Pagebuilder/issues/8#issuecomment-625410309

**Comment by kousar2334** [comment]
![Screenshot_2020-06-28_19-35-25](https://user-images.githubusercontent.com/23190775/85949118-b4463180-b976-11ea-90e4-9c57584f0ad0.png)
![Screenshot_2020-06-28_19-35-49](https://user-images.githubusercontent.com/23190775/85949121-b90ae580-b976-11ea-8a50-f6f0034b00cb.png)
![Screenshot_2020-06-28_19-36-23](https://user-images.githubusercontent.com/23190775/85949122-b9a37c00-b976-11ea-9ba3-efa3390988e3.png)
Can I make this kind of grid system using this package?

**Comment by HansSchouten** [comment]
Yes it is possible, however the "select your structure" that you showed is not yet supported. But good suggestion!
For now you can do this in your view file (if you included bootstrap):

```
<div class="row">
    <div class="col-md-6" phpb-blocks-container></div>
    <div class="col-md-6" phpb-blocks-container></div>
</div>
```

So for now you can just create a separate block for any grid variant you want to have.
