### ISSUE TITLE
Pagebuilder offline

### ISSUE THREAD

**Issue by adeguntoro** [HansSchouten/Laravel-Pagebuilder#24]
Which file i need to change to make it work offline ? I want to work offline ( for testing ) because i have poor internet connectivity. I just want to use offline bootstrap from app.css and app.js.

**Comment by HansSchouten** [comment]
Hi, good suggestion. I am planning to remove all CDN links. The files to change are:

- https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/GrapesJS/resources/views/layout.php
- https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/GrapesJS/resources/views/pagebuilder.php
- https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/WebsiteManager/resources/layouts/empty.php
- https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/WebsiteManager/resources/layouts/master.php
- https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/Auth/resources/views/layout.php

However, at the moment I did not have time to change this myself. So for now you have to modify it yourself.
