### ISSUE TITLE
Grid system into block

### ISSUE THREAD

**Issue by kousar2334** [HansSchouten/Laravel-Pagebuilder#25]
I have created a block named section, view.php
```
<div class="row">
    <div class="col-md-6" phpb-blocks-container>
    	
    </div>
    <div class="col-md-6" phpb-blocks-container>
    	
    </div>
</div>

```
the another block is hello, view.php is
`<p>Hello</p>`

First I added section block then I want to add hello block inside section block , but it is not working properly. 
![Screenshot_2020-06-29_12-52-03](https://user-images.githubusercontent.com/23190775/85982314-6c231f80-ba07-11ea-8b6a-70eb7fa405fa.png)
The two hello block go two different row.

**Comment by HansSchouten** [comment]
This is not working in a .php block, you should change your section block to .html.

**Comment by kousar2334** [comment]
thanks it works
