### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by mansmahamat** [HansSchouten/Laravel-Pagebuilder#26]
<img width="1640" alt="2020-06-29" src="https://user-images.githubusercontent.com/58693907/86027855-807c1200-ba31-11ea-8404-b2aaf4404665.png">

Hello i follow instructions from Read me but don't still work

**Comment by kousar2334** [comment]
After modify .env file restart the server, It maybe work.

**Comment by HansSchouten** [comment]
For me the installation steps give a working environment, locally on Windows and on Linux, so I guess it would be related to the environment you installed to project in. I suggest you to debug the output of the phpb_ helper methods https://github.com/HansSchouten/Laravel-Pagebuilder/issues/10.

**Comment by mansmahamat** [comment]
Thanks for reply its work fine
