### ISSUE TITLE
Dynamic option in config.php for block setting 

### ISSUE THREAD

**Issue by kousar2334** [HansSchouten/Laravel-Pagebuilder#27]
I have written this code into config.php for block setting
```
`<?php
use App\Http\Controllers\backend\PageController;
$ctrl=new PageController();
$categories=$ctrl->getCategories();
return [
    'title' => 'Banner',
    'category' => 'Banner',
    'icon' => 'fa fa-server',
    "settings" => [
      "first-section" => [
            "type" => "select",
            "label" => "Select First Block Category",
            "options" =>$categories,
        ],  `
```
Code in controller 
```
public function getCategories()
   {
   	$cats=DB::table('news_categories')->select('name')->get();
   	return $cats;
   }
The output is 
```
![Screenshot_2020-06-29_23-11-35](https://user-images.githubusercontent.com/23190775/86083621-9e428900-babc-11ea-9623-054b3667b397.png)
![Screenshot_2020-06-29_23-11-59](https://user-images.githubusercontent.com/23190775/86083626-9f73b600-babc-11ea-8ace-cf6b2bfe08c0.png)

Why the option's value is undefined. Please help ..

**Comment by HansSchouten** [comment]
This is the code that sets your custom selector options: https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/GrapesJS/Block/BlockAdapter.php#L136. If you look a few lines further, it shows the expected format. I guess you don't have an id key in the array.

**Comment by RishiWebVeerIT** [comment]
How can I add Js and CSS in the master file via config or view.php file
