### ISSUE TITLE
Builder

### ISSUE THREAD

**Issue by mansmahamat** [HansSchouten/Laravel-Pagebuilder#28]
Hello is it possible to generate an html file with the data from the database?

**Comment by HansSchouten** [comment]
Hi, yes this is possible by calling the `PageRenderer` class. There are some recent issues in this repo or the PHPageBuilder repo that show code that generates a html string.

**Comment by mansmahamat** [comment]
yes i see but i don't know where paste this code : 

    public function viewPage($pageId)
{
	$theme = new Theme(config('pagebuilder.theme'), config('pagebuilder.theme.active_theme'));
	$page = (new PageRepository)->findWithId($pageId);
	$pageRenderer = new PageRenderer($theme, $page);
	$html = $pageRenderer->render();
	return $html;
}

**Comment by HansSchouten** [comment]
As a custom controller method.
