### ISSUE TITLE
how to direct my old routes

### ISSUE THREAD

**Issue by alifu** [HansSchouten/Laravel-Pagebuilder#3]
HI, can you explain how to use routes? because all my route is going to phpagebuilder routes

**Comment by HansSchouten** [comment]
Currently the package by default relies on routes from the pages table. This is handled in `PHPageBuilder\Modules\Router\DatabasePageRouter` which you could also replace by implementing `RouterContract` and adding your custom router class to the pagebuilder config file. I see now that at the moment it is not possible to break out of this and use your existing Laravel routes (see how all types of routes are handled in `PHPageBuilder\PHPageBuilder->handleRequest()`). I guess it is desirable to be able to disable the `DatabasePageRouter` altogether, which allows the original Laravel routes to be evaluated?

**Comment by HansSchouten** [comment]
I just created a new release with a `use_router` setting for disabling the default PHPageBuilder router. If you set `router > use_router` to `false`, all standard Laravel routes are evaluated.
