### ISSUE TITLE
How to Skip some routes from going to WebsiteController@uri

### ISSUE THREAD

**Issue by SoftHeroes** [HansSchouten/Laravel-Pagebuilder#30]
Hello @HansSchouten 

I just follow [this](https://github.com/HansSchouten/Laravel-Pagebuilder/issues/8) guide. And everything is working fine. But my old route Like **'http://example.test/my-admin/login'** this route also handle by **WebsiteController@uri** method.

I just want some URL's to ignore to going that method.

Can you help me to do that

**Comment by SoftHeroes** [comment]
I just did some trick to work around this as bellow.

```
Route::any('/{uri}', [
    'uses' => 'WebsiteController@uri',
    'as' => 'page',
])->where('uri', '^((?!<1-route>|<12-route>|<3-route>|....|<n-route>).)*$');

```

Hey, @HansSchouten  

I am not closing this issue maybe you may give a better solution.
If you feel you can close this. but I suggest just add param in the config for the route to skip or option to a prefix of the route(or array for routes path).

**Comment by HansSchouten** [comment]
Hi @SoftHeroes,

What I usually do is ensure this is the last route, so all other matches will be handled first and this is a sort of catch-all.
But I will consider the config suggestion, sounds like another usefull way for some situations.
