### ISSUE TITLE
Add action

### ISSUE THREAD

**Issue by Hero555007** [HansSchouten/Laravel-Pagebuilder#32]
Hi, HansSchouten. I am pleasure your pagbuilder. and then how can I add the carousel function in your project.

**Comment by HansSchouten** [comment]
Hi, thanks. You can add a carousel by creating a new block. This can be done by creating a new folder in your theme's folder with the name of your block. Next add a .html file that contains the html structure of your carousel and also the script that is needed to start the carousel. This should be possible, see this example: https://www.gambiabirdingtours.com/en.
