### ISSUE TITLE
Have a error on Laravel 7.

### ISSUE THREAD

**Issue by loukasstoltz** [HansSchouten/Laravel-Pagebuilder#34]
Hi, 
I try to install it on Laravel 7 with Auth UI, 
I have the /admin access, 
I have add a user with admin role wich is active on DataBase, but when i try to login with Username (or Mail?) and PW, it return always the false response... 

i have made a php artisan migrate:fresh
Add the user manually 
Could you please help me to solve that ?  

![Capture d’écran 2020-09-01 à 10 56 08](https://user-images.githubusercontent.com/19878463/91829434-c330b500-ec41-11ea-8dcb-cb252d20a31d.png)

**Comment by HansSchouten** [comment]
The website manager is currently just a basic manager consisting of a few lines of core PHP code, directly from https://github.com/HansSchouten/PHPageBuilder. So it is not using any Laravel functionality. The username, password is configured in your phpagebuilder config file. I would suggest for now to integrate the project into your own Laravel backend and ignore (disable) the website manager.

**Comment by loukasstoltz** [comment]
hi @HansSchouten ,
thank you for your support ! 
I will try it tomorrow :-) 
Thank you !
