### ISSUE TITLE
Plz add Laravel 8 Support

### ISSUE THREAD

**Issue by ClickerVinod** [HansSchouten/Laravel-Pagebuilder#36]
Hi,

Plz add Laravel 8 Support

Thanks

**Comment by malinga91** [comment]
Yes please. When I view the page, returning an empty white page.

**Comment by ClickerVinod** [comment]
> Yes, please. When I view the page, returning an empty white page.

@malinga91  I'm also getting a blank page tried different thing but nothing happens, only 127.0.0.1:8000/admin/auth  and 127.0.0.1:8000/admin/pagebuilder?page=1working  saving but preview also not working.
No other pages loading related to laravel

**Comment by malinga91** [comment]
@ClickerVinod Same thing happened for me.

**Comment by dboldbaatar** [comment]
laravel 8 is running. Not Problem !

**Comment by michaelyue** [comment]
@dboldbaatar how did you make it running in Laravel 8 ,
I got the error when try to publish demo :
  UnexpectedValueException

  DirectoryIterator::__construct(F:\mao\DigitalJungle\projects\proj_usyd\ecosystem\web\ecosys\themes/demo/blocks,F:\mao\DigitalJungle\projects\proj_usyd\ecosystem\web\ecosys\themes/demo/blocks): The system cannot find the path specified. (code: 3)

  at F:\mao\DigitalJungle\projects\proj_usyd\ecosystem\web\ecosys\vendor\hansschouten\phpagebuilder\src\Theme.php:51
     47▕      */
     48▕     protected function loadThemeBlocks()
     49▕     {
     50▕         $this->blocks = [];
  ➜  51▕         $blocksDirectory = new DirectoryIterator($this->getFolder() . '/blocks');
     52▕         foreach ($blocksDirectory as $entry) {
     53▕             if ($entry->isDir() && ! $entry->isDot()) {
     54▕                 $blockSlug = $entry->getFilename();
     55▕                 $block = new ThemeBlock($this, $blockSlug);

  1   F:\mao\DigitalJungle\projects\proj_usyd\ecosystem\web\ecosys\vendor\hansschouten\phpagebuilder\src\Theme.php:51
      DirectoryIterator::__construct("F:\mao\DigitalJungle\projects\proj_usyd\ecosystem\web\ecosys\themes/demo/blocks")

  2   F:\mao\DigitalJungle\projects\proj_usyd\ecosystem\web\ecosys\vendor\hansschouten\phpagebuilder\src\Theme.php:41
      PHPageBuilder\Theme::loadThemeBlocks()

**Comment by HansSchouten** [comment]
@michaelyue your error has just been fixed in [v0.15.0](https://github.com/HansSchouten/Laravel-Pagebuilder/releases/tag/v0.15.0). Please upgrade your environment.
