### ISSUE TITLE
NOT WORK

### ISSUE THREAD

**Issue by mokochweb** [HansSchouten/Laravel-Pagebuilder#39]
installation not work screen are white... Not funny

**Comment by mokochweb** [comment]
I follow all steps for in stall after config file to set use_login, use_website_manager and use_router to false. after i created table pagebuilder__pages  im do this: 

routes\web.php

Route::any('/admin/pages/{id}/build', 'App\Http\Controllers\PageBuilderController@build')->name('pagebuilder.build');
Route::any('/admin/pages/build', 'App\Http\Controllers\PageBuilderController@build');

config\pagebuilder.php

'pagebuilder' => [
	'class' => PHPageBuilder\Modules\GrapesJS\PageBuilder::class,
	'url' => '/admin/pages/build',      // the route you created for your pagebuilder controller
	'actions' => [
		'back' => '/admin/pages'    // URL to a table overview of all pages
	]
],

App\Providers\AppServiceProvider.php boot method

// register singleton phppagebuilder (this ensures all phpb_ helpers have the right config without first manually creating a pagebuilder instance)
$this->app->singleton('phpPageBuilder', function($app) {
    return new PHPageBuilder(config('pagebuilder'));
});
$this->app->make('phpPageBuilder');

resources\views\pagebuilder\scripts.blade.php

<script type="text/javascript">
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
        }
    });

    window.customConfig = {
        assetManager: {
            headers: {
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
            }
        }
    };
</script>

App\Http\Controllers\PageBuilderController.php

/**
 * Edit the given page with the page builder.
 *
 * @param int|null $pageId
 * @throws Throwable
 */
public function build($pageId = null)
{
    $route = $_GET['route'] ?? null;
    $action = $_GET['action'] ?? null;
    $pageId = is_numeric($pageId) ? $pageId : ($_GET['page'] ?? null);
    $pageRepository = new \PHPageBuilder\Repositories\PageRepository;
    $page = $pageRepository->findWithId($pageId);

    $phpPageBuilder = app()->make('phpPageBuilder');
    $pageBuilder = $phpPageBuilder->getPageBuilder();

    $customScripts = view("pagebuilder.scripts")->render();
    $pageBuilder->customScripts('head', $customScripts);

    $pageBuilder->handleRequest($route, $action, $page);
}

To publicly serve all pages
routes\web.php

Add this at the bottom of your routes file

Route::any('{uri}', [
    'uses' => 'App\Http\Controllers\WebsiteController@uri',
    'as' => 'page',
])->where('uri', '.*');

App\Http\Controllers\WebsiteController.php

/**
 * Show the website page that corresponds with the current URI.
 */
public function uri()
{
    $pageBuilder = app()->make('phpPageBuilder');
    $pageBuilder->handlePublicRequest();
}



AND after when i go in /admin i have error :
Authentication is disabled, use handlePublicRequest() and handleAuthenticatedRequest()

How i can leave this?

**Comment by HansSchouten** [comment]
Searching on the error message in the project would have pointed you to `PHPageBuilder.php:252`:
```
if (! phpb_config('auth.use_login') || ! phpb_config('website_manager.use_website_manager')) {
	die('Authentication is disabled, use handlePublicRequest() and handleAuthenticatedRequest()');
}
```
This indicates that you have login disabled, or you have the website manager disabled.
Since in this case `$pageBuilder->handleRequest($route, $action, $page);` does not perform any auth checks, you should call `handlePublicRequest()` for your public requests (you are already doing this) and you should call `handleAuthenticatedRequest()` for the pagebuilder/backend related routes. You are not doing this in your `build($pageId = null)` method.
So please use `handleAuthenticatedRequest()` in your build method.
