### ISSUE TITLE
Fresh installation in laravel 6 are coming without themes folder

### ISSUE THREAD

**Issue by marcospmuniz** [HansSchouten/Laravel-Pagebuilder#4]
I just installed Laravel 6 + pagebuilder and to my surprise, it doesn't work because the themes and blocks were not created during the installation process, which causes an error even in /admin/auth

UnexpectedValueException
DirectoryIterator::__construct(/home/marcos/www/pagebuilders/laravel6-pagebuilder/themes/demo/blocks): failed to open dir: No such file or directory

**Comment by HansSchouten** [comment]
Hi Marcos, yes that is true. After adding the pagebuilder, you can follow the steps here: https://github.com/HansSchouten/PHPagebuilder#create-a-theme to create a theme. However, I could add a publish command that does add the demo theme. I will look into that.

**Comment by HansSchouten** [comment]
I just released a new version with a command to create a new theme and the ability to publish the demo theme.
