### ISSUE TITLE
Please PostgreSQL support

### ISSUE THREAD

**Issue by dboldbaatar** [HansSchouten/Laravel-Pagebuilder#43]
Please PostgreSQL support

My Solution :)
phppagebuilder/src/Core/DB.php
if($config['driver'] == 'pgsql'){
            $this->pdo = new PDO(
                $config['driver'] . ':host=' . $config['host'] . ';dbname=' . $config['database'],
                $config['username'],
                $config['password'],
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );
        }else{
            $this->pdo = new PDO(
                $config['driver'] . ':host=' . $config['host'] . ';dbname=' . $config['database'] . ';charset=' . $config['charset'],
                $config['username'],
                $config['password'],
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );
}

**Comment by HansSchouten** [comment]
Good suggestion, I will add it to PHPageBuilder.

**Comment by HansSchouten** [comment]
I see now the only difference is the charset. Does this give an exception with postgres?

**Comment by dboldbaatar** [comment]
SQLSTATE[08006] [7] invalid connection option "charset"

![Screenshot from 2020-10-20 14-56-31](https://user-images.githubusercontent.com/10512218/96551271-97968680-12e4-11eb-9171-05ba57be2f88.png)

**Comment by HansSchouten** [comment]
I fixed it here: https://github.com/HansSchouten/PHPageBuilder/commit/bd1cd30ad28320fc2b8cc4a3ae5ba97cfb090891
Can you confirm that using this snippet solves your issue? I will add it in the next release.
