### ISSUE TITLE
Error (composer require hansschouten/laravel-pagebuilder)

### ISSUE THREAD

**Issue by Andreidavid918** [HansSchouten/Laravel-Pagebuilder#44]
Hi . I created a new laravel project by using this command `composer create-project --prefer-dist laravel/laravel chat` and after I created the project I used the command `composer require hansschouten/laravel-pagebuilder` and I get this error : 

```
D:\xampp\htdocs\laravel\chat>composer require hansschouten/laravel-pagebuilder
Using version ^0.13.0 for hansschouten/laravel-pagebuilder
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing hansschouten/phpagebuilder (v0.13.0): Loading from cache
  - Installing hansschouten/laravel-pagebuilder (v0.13.0): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   TypeError

  Argument 1 passed to PHPageBuilder\PHPageBuilder::__construct() must be of the type array, null given, called in D:\xampp\htdocs\laravel\chat\vendor\hansschouten\laravel-pagebuilder\src\ServiceProvider.php on line 43

  at D:\xampp\htdocs\laravel\chat\vendor\hansschouten\phpagebuilder\src\PHPageBuilder.php:47
     43▕      * PHPageBuilder constructor.
     44▕      *
     45▕      * @param array $config         configuration in the format defined in config/config.example.php
     46▕      */
  ➜  47▕     public function __construct(array $config)
     48▕     {
     49▕         if (session_status() === PHP_SESSION_NONE) {
     50▕             session_start();
     51▕         }

  1   D:\xampp\htdocs\laravel\chat\vendor\hansschouten\laravel-pagebuilder\src\ServiceProvider.php:43
      PHPageBuilder\PHPageBuilder::__construct()

  2   D:\xampp\htdocs\laravel\chat\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
      HansSchouten\LaravelPageBuilder\ServiceProvider::HansSchouten\LaravelPageBuilder\{closure}(Object(Illuminate\Foundation\Application), [])
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
```

Any idea how can I solve this issue ? Sorry if I made any newbie mistakes . I come from a Python(Flask) background and I've never worked with laravel. Would be great if you could make some videos about this content management system.
Thank you

**Comment by HansSchouten** [comment]
Please see this solution: https://github.com/HansSchouten/Laravel-Pagebuilder/issues/41#issuecomment-713259792

Currently I am busy using the project for my initial customers, but I am planning to make the project more easy to use in the future.

**Comment by dartoran** [comment]
> Please see this solution: [#41 (comment)](https://github.com/HansSchouten/Laravel-Pagebuilder/issues/41#issuecomment-713259792)

Hello World
I have the same problem here and the solution #41 doesn't work for me. With these prints, can you tell me if I'm doing something wrong? 
![image](https://user-images.githubusercontent.com/72527800/96725413-3b387300-1387-11eb-9477-8f4ca92d5a1b.png)
![image](https://user-images.githubusercontent.com/72527800/96725730-92d6de80-1387-11eb-8835-7a1b21faccf5.png)
![image](https://user-images.githubusercontent.com/72527800/96725770-a2562780-1387-11eb-9fef-b02d51589cbe.png)

**Comment by dartoran** [comment]
Well, with this issue closed, I will open another one.
