### ISSUE TITLE
"__construct() must be of the type array, null give" in PHPageBuilder.php:47

### ISSUE THREAD

**Issue by dartoran** [HansSchouten/Laravel-Pagebuilder#45]
Hello World
I have the same problem here and the solution #41 doesn't work for me. With these prints, can you tell me if I'm doing something wrong?

![image](https://user-images.githubusercontent.com/72527800/96726464-653e6500-1388-11eb-8dc1-e19dbc3cea68.png)
![image](https://user-images.githubusercontent.com/72527800/96726557-76877180-1388-11eb-8608-487c60b62b07.png)
![image](https://user-images.githubusercontent.com/72527800/96726643-8e5ef580-1388-11eb-8348-beb5e8976a4c.png)

**Comment by dedeardiansya** [comment]
same issue T_T

**Comment by MicVital** [comment]
Same issue here. I can't even publish the config file afterwards

**Comment by dedeardiansya** [comment]
I don't think this package supports the new version of laravel.

**Comment by HansSchouten** [comment]
That could be the case. I am currently working with Laravel 6 on all my websites and haven't made the time to upgrade or tryout the package in the latest Laravel yet.
