### ISSUE TITLE
 PHPageBuilder\PHPageBuilder::__construct() must be of the type array, null given

### ISSUE THREAD

**Issue by josh-whit-me** [HansSchouten/Laravel-Pagebuilder#48]
I have encountered an error while installing Laravel-Pagebuilder.
My laravel version is 8

	  > Illuminate\Foundation\ComposerScripts::postAutoloadDump

		@php artisan package:discover --ansi

	TypeError

	Argument 1 passed to PHPageBuilder\PHPageBuilder::__construct() must be of the type array, null given, called in C:\directory\laravel\vendor\hansschouten\laravel-pagebuilder\src\ServiceProvider.php on line 43

	at C:\directory\laravel\vendor\hansschouten\phpagebuilder\src\PHPageBuilder.php:47
	43? * PHPageBuilder constructor.
	44? *
	45? * @param array $config configuration in the format defined in config/config.example.php
	46? */
	? 47? public function __construct(array $config)
	48? {
	49? if (session_status() === PHP_SESSION_NONE) {
	50? session_start();
	51? }

	1 C:\directory\laravel\vendor\hansschouten\laravel-pagebuilder\src\ServiceProvider.php:43
	PHPageBuilder\PHPageBuilder::__construct()

	2 C:\directory\laravel\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
	HansSchouten\LaravelPageBuilder\ServiceProvider::HansSchouten\LaravelPageBuilder{closure}(Object(Illuminate\Foundation\Application), [])
	Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

	Installation failed, reverting ./composer.json to its original content.

**Comment by michaelyue** [comment]
I got the same issue with Laravel 8 in XAMPP in Windows 10

**Comment by michaelyue** [comment]
> I have encountered an error while installing Laravel-Pagebuilder.
> My laravel version is 8
> 
> ```
>   > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> 
> 	@php artisan package:discover --ansi
> 
> TypeError
> 
> Argument 1 passed to PHPageBuilder\PHPageBuilder::__construct() must be of the type array, null given, called in C:\directory\laravel\vendor\hansschouten\laravel-pagebuilder\src\ServiceProvider.php on line 43
> 
> at C:\directory\laravel\vendor\hansschouten\phpagebuilder\src\PHPageBuilder.php:47
> 43? * PHPageBuilder constructor.
> 44? *
> 45? * @param array $config configuration in the format defined in config/config.example.php
> 46? */
> ? 47? public function __construct(array $config)
> 48? {
> 49? if (session_status() === PHP_SESSION_NONE) {
> 50? session_start();
> 51? }
> 
> 1 C:\directory\laravel\vendor\hansschouten\laravel-pagebuilder\src\ServiceProvider.php:43
> PHPageBuilder\PHPageBuilder::__construct()
> 
> 2 C:\directory\laravel\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
> HansSchouten\LaravelPageBuilder\ServiceProvider::HansSchouten\LaravelPageBuilder{closure}(Object(Illuminate\Foundation\Application), [])
> Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
> 
> Installation failed, reverting ./composer.json to its original content.
> ```

@josh-whit-me Did you find any solution?

**Comment by HansSchouten** [comment]
It seems like the configuration is not passed while instantiating the `PHPageBuilder` object over here https://github.com/HansSchouten/Laravel-Pagebuilder/blob/master/src/ServiceProvider.php#L43. Can you have a look why `config('pagebuilder')` is empty?

**Comment by tykus** [comment]
Same issue - this is happening **on installation with composer**, there is not opportunity to publish config.  

I added a `pagbuilder.php` config file returning an empty array to change the error; which it did...

```
> @php artisan package:discover --ansi

   ErrorException

  Undefined index: SERVER_NAME

  at vendor/hansschouten/phpagebuilder/src/Core/helpers.php:247
    243▕         $port = '';
    244▕         if (isset($_SERVER['SERVER_PORT']) && ! in_array($_SERVER['SERVER_PORT'], [80, 443])) {
    245▕             $port = ":" . $_SERVER['SERVER_PORT'];
    246▕         }
  ➜ 247▕         $currentFullUrl = $protocol . "://" . $_SERVER['SERVER_NAME'] . $port . urldecode($_SERVER['REQUEST_URI']);
    248▕         $currentFullUrl = rtrim($currentFullUrl, '/' . DIRECTORY_SEPARATOR);
    249▕         return $currentFullUrl;
    250▕     }
    251▕ }

      +18 vendor frames
  19  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(HansSchouten\LaravelPageBuilder\ServiceProvider))

      +5 vendor frames
  25  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
