### ISSUE TITLE
Cant login admin Page Builder

### ISSUE THREAD

**Issue by meesudzu** [HansSchouten/Laravel-Pagebuilder#5]
It always return "Page not found". I have change all urls in config. 
But it doesn't work.

**Comment by HansSchouten** [comment]
Are you using a correctly functioning Laravel installation? For new Laravel installations you would see a default Laravel page after installation and after adding Laravel-Pagebuilder it would currently result in a 500 server error untill you have created a theme (via [these steps](https://github.com/HansSchouten/PHPagebuilder#create-a-theme)). After adding a `themes` folder with a default `demo` theme and master layout, you should be able to login via `/admin`. Is that working?

**Comment by meesudzu** [comment]
Yep,
It's correctly installation and has show a login page with url has defined in config.
But when i fill username & password, then submit, it's just return "Page not found".

**Comment by HansSchouten** [comment]
Can you ensure you are using the latest release: v0.4.0? And did you run the migrations? I just installed it on a clean Laravel installation and everything works fine. Otherwise you could set some breakpoints in the `PHPageBuilder\Modules\Auth\Auth` class and see where things go wrong. After login it should redirect using: `phpb_redirect(phpb_url('website_manager'));`, which should resolve to `/admin`.

**Comment by meesudzu** [comment]
Thanks.
Maybe it's conflict with my old project.
I'll try on a clean Project.

**Comment by meesudzu** [comment]
![Screenshot from 2020-03-14 08-46-40](https://user-images.githubusercontent.com/17334624/76672588-72180080-65d0-11ea-90ba-f04cd1d5ef29.png)
As you can see. The form's action has an invalid url after install. But when I change form's action to "lvh.me/admin" in config. Then submit, It's return a "Page not found"
![Screenshot from 2020-03-14 08-47-09](https://user-images.githubusercontent.com/17334624/76672614-abe90700-65d0-11ea-96b7-ecc3e837efc5.png)
I'll install debugbar then check again.

**Comment by meesudzu** [comment]
I has found the problem when login.
In PHPageBuilder\Modules\Auth@handleRequest,
`if (phpb_in_module('auth') && $action === 'login' && isset($_POST['username']) && isset($_POST['password'])) {...}`
phpb_in_module('auth') always return 'false'.

**Comment by meesudzu** [comment]
And after use a few minutes. I found a lot of errors with routes,
like: admin/?route=page_settings&action=create

**Comment by meesudzu** [comment]
Error in helper's function phpb_in_module().
`
$url = phpb_url($module, [], false);  
$currentUrl = explode('?', urldecode($_SERVER['REQUEST_URI']), 2)[0];  
return $currentUrl === $url;
`
$url always return: '/admin/auth'  
and $curentUrl always return: '/admin/'  
so the function always return false. Then all request return "Page not found"

**Comment by meesudzu** [comment]
And finaly.
I can't access to pagebuild to edit page.
It's always goto WebsiteManager@handleRequest.
Then catch in case `if (is_null($route)) {
            $this->renderOverview();
            exit();
        }` 
and just show the all pages overview
![Screenshot from 2020-03-14 09-49-01](https://user-images.githubusercontent.com/17334624/76673578-0c7c4200-65d9-11ea-8c7e-d2c1930705c1.png)

**Comment by HansSchouten** [comment]
For redirecting to the different pages and checking which page is active, the `$_SERVER['REQUEST_URI']` and `$_SERVER['SERVER_NAME']` server variables are used. Could you check whether these are set? The fact that the login form redirects to `http:///admin/auth?action=login` suggests it does not contain a value.

**Comment by codegeek1001** [comment]
Can we not use the env('APP_URL') env. variable in this case instead ?

**Comment by HansSchouten** [comment]
This repository is a simple wrapper around the [PHPageBuilder](https://github.com/HansSchouten/PHPageBuilder) project which is PHP framework independent. `$_SERVER['SERVER_NAME']` is used [here](https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Core/helpers.php#L217). However, I can add a similar config setting and in this Laravel project set its default to `env('APP_URL)`. Thanks for the suggestion, I will add it this week.
