### ISSUE TITLE
> Error: **Undefined index: REQUEST_URI** and **Undefined index: SERVER_NAME** in **hansschouten\phpagebuilder\src\Core\helpers.php line 247**

### ISSUE THREAD

**Issue by vincent-ikonk** [HansSchouten/Laravel-Pagebuilder#52]
> Error: **Undefined index: REQUEST_URI** and **Undefined index: SERVER_NAME** in **hansschouten\phpagebuilder\src\Core\helpers.php line 247**
> 
> I changed line 247 to **$currentFullUrl = $protocol . "://" . request()->server('SERVER_NAME') . $port . urldecode(request()->server('REQUEST_URI'));** and it work
> 
> * Laravel 6
> * PHP 7.3
> * centOS 7

Also worked for me

_Originally posted by @vdvcoder in https://github.com/HansSchouten/Laravel-Pagebuilder/issues/42#issuecomment-715919719_

**Comment by akbarabustang** [comment]
Hi
Do we need to fix the code ?

**Comment by HansSchouten** [comment]
This issue has just been fixed in [v0.15.0](https://github.com/HansSchouten/Laravel-Pagebuilder/releases/tag/v0.15.0). Please upgrade your environment.
