### ISSUE TITLE
No PHPageBuilder config found after update to 0.15.0

### ISSUE THREAD

**Issue by Dontorpedo** [HansSchouten/Laravel-Pagebuilder#54]
Hi after update to the newest version an error appears 

`No PHPageBuilder config found, please run: php artisan vendor:publish --provider="HansSchouten\LaravelPageBuilder\ServiceProvider" --tag=config `

but the config file exists, even after running the command again, error still there

**Comment by dsultanr** [comment]
same here

**Comment by HansSchouten** [comment]
I see I made a mistake, I am fixing it now.

**Comment by HansSchouten** [comment]
It should be fixed now

**Comment by Dontorpedo** [comment]
yup, it works now, i updated same file. thanks

**Comment by dsultanr** [comment]
increase the version number please

**Comment by HansSchouten** [comment]
I removed the v0.15.0 from packagist, readded the tag and did a `composer update`. For me it resolved the issue with the same release version number.

**Comment by dsultanr** [comment]
composer update not updating anything. should I remove your package from composer.json update, readd and then again update?

**Comment by dsultanr** [comment]
rm -rf vendor/hansschouten/laravel-pagebuilder/ && composer update hansschouten/laravel-pagebuilder did the trick
