### ISSUE TITLE
getting missing js file

### ISSUE THREAD

**Issue by dev-shack** [HansSchouten/Laravel-Pagebuilder#56]
Hello! just getting this error, it was working fine, I am not sure what has happened with this installation?
![image](https://user-images.githubusercontent.com/72554123/100471695-9edb5c00-30fc-11eb-89d2-356ddc83e3fe.png)

**Comment by HansSchouten** [comment]
To be honest I don't know as well. Maybe try updating the package to the latest version? Or try to debug what is happening.

**Comment by mh-technologies** [comment]
Okay, thanks, will try to update the package and debug it.

**Comment by esvikas** [comment]
Did you find any solution?
