### ISSUE TITLE
Couldn't change database connection port number

### ISSUE THREAD

**Issue by johnyang90** [HansSchouten/Laravel-Pagebuilder#59]
I am using MAMP as my local server and my default database port is 8889, when i tried to do php artisan migrate, it shows db connection refused. But when i change my mysql server port to 3306, it works. 

So I suggest to add a flexibility to configure DB port number.

**Comment by HansSchouten** [comment]
Hi, yesterday I merged a PR and I think that solves your problem: https://github.com/HansSchouten/Laravel-Pagebuilder/commit/5e22bfe086ee92187e5345270105d3fa42162b3b.
I will create a release very soon.
