### ISSUE TITLE
DirectoryIterator error code: 3!  Error in Theme.php

### ISSUE THREAD

**Issue by maksakoviliya** [HansSchouten/Laravel-Pagebuilder#6]
DirectoryIterator::__construct(F:\4work\test\blog\themes/demo/blocks,F:\4work\test\blog\themes/demo/blocks): ������� �� ������ ����� �������� ���. (code: 3)

it is empty laravel 6 installation. Only php artisan serve command executed. 

Can you help me?

**Comment by HansSchouten** [comment]
Hi, this is because the themes folder is missing. You first need to create a theme. I just created a new release with a command to create a theme. See readme for more information.

**Comment by maksakoviliya** [comment]
I have installed new release, but there is error. Themes folder isn't empty(( 
![image](https://user-images.githubusercontent.com/16371638/77233687-2eb62700-6bba-11ea-9ce2-9738434c8321.png)
![image](https://user-images.githubusercontent.com/16371638/77233697-442b5100-6bba-11ea-9176-fc07223ff79b.png)
![image](https://user-images.githubusercontent.com/16371638/77233711-61f8b600-6bba-11ea-8e68-26fff89d78ed.png)

Cache cleared.

**Comment by HansSchouten** [comment]
First of all your error messages are really unclear which makes your life harder while debugging. I have never seen such weird characters instead I get very clear messages to what is going wrong, so maybe use another webserver or fix that. But I do see the message pointing to Theme.php line number 51: `$blocksDirectory = new DirectoryIterator($this->getFolder() . '/blocks');`, so if you could check what is inside `$this->getFolder()` over there, I expect something is going wrong there.

**Comment by maksakoviliya** [comment]
dd($this->getFolder()) prints 'F:\4work\govorenglish\themes/demo'
But if i'll try o do dd($blocksDirectory); after creating of new instance of DirectoryIterator there is same error(( May be it is bug in slashes? Why they are different& Some of them are straight "/" ? and some of them are returned "\" ??

**Comment by teddollard** [comment]
hi
![image](https://user-images.githubusercontent.com/62069761/77314434-87420d00-6cfd-11ea-98d1-add6e6f29065.png)
can you help me?

**Comment by HansSchouten** [comment]
Hi! I think your issue is unrelated to this, but it seems like you first need to complete your laravel installation itself (create a database before running the migrations).

**Comment by HansSchouten** [comment]
> But if i'll try o do dd($blocksDirectory); after creating of new instance of DirectoryIterator there is same error(( May be it is bug in slashes?

So the problem is in instantiating the DirectoryIterator, could you try manually passing `F:\4work\govorenglish\themes\demo` to the iterator to see if it is working? I don't have a Windows environment around to see whether this is an issue

**Comment by teddollard** [comment]
thank you.
![image](https://user-images.githubusercontent.com/62069761/77319932-962dbd00-6d07-11ea-9047-a32b3b7d3ef1.png)

**Comment by HansSchouten** [comment]
Hmm this indeed seems like the same issue, could you try to debug Theme.php by replacing line 51 for `$blocksDirectory = new DirectoryIterator('F:\312\laravel\blog\themes\demo\blocks');`.

**Comment by maksakoviliya** [comment]
No, there is no difference. Both straigth and reverse slashes goes to same error((

**Comment by HansSchouten** [comment]
Ok nice, so that is ruled out. And maybe adding a trailing slash to the path? If you could debug why the DirectoryIterator is not finding the folder I am happy to correct it in the code.

**Comment by teddollard** [comment]
hi
can you please upload video guide?
thank you

**Comment by HansSchouten** [comment]
Hi, yes eventually I would like to make this available, but currently this project is still not with a stable release version. A lot will be done in the upcoming months. However, related to the problem here I cannot replicate it. I expect it to be something related to the web servers & OS you are using, but I don't know yet the exact cause. If any of you could get the DirectoryIterator to work than I will know how to solve it.
