### ISSUE TITLE
Err while using custom route in pagebuilder config

### ISSUE THREAD

**Issue by macgadger** [HansSchouten/Laravel-Pagebuilder#60]
I am trying to use my own auth and crm. While i am logged into my CRM. I updated the url of pagebuilder config to

`'pagebuilder' => [
        'class' => PHPageBuilder\Modules\GrapesJS\PageBuilder::class,
        'url' => '/app/page/edit',
        'actions' => [
            'back' => '/app/page/index'
        ]
   ],`

while accessing this url i am getting this error 

`Authentication is disabled, use handlePublicRequest() and handleAuthenticatedRequest()`

Please update on this Thanks!

**Comment by HansSchouten** [comment]
This means you have disabled the default authentication module. Therefore you need to provide your own controller methods, one that is a catch all request for all website pages which calls handlePublicRequest(). And one controller method for the pagebuilder in which you check that the user is authenticated and then calls handleAuthenticatedRequest().

Here you can read more details: https://github.com/HansSchouten/Laravel-Pagebuilder/issues/8

**Comment by macgadger** [comment]
> This means you have disabled the default authentication module. Therefore you need to provide your own controller methods, one that is a catch all request for all website pages which calls handlePublicRequest(). And one controller method for the pagebuilder in which you check that the user is authenticated and then calls handleAuthenticatedRequest().
> 
> Here you can read more details: #8

Thanks for Reply, i followed the #8 and end up with this error while registering singlton:

`Error
Class 'App\Providers\PHPageBuilder' not found`

on AppServiceProvider

` public function register()
    {
        //
        $this->app->singleton('phpPageBuilder', function($app) {
            return new PHPageBuilder(config('pagebuilder'));
        });
        $this->app->make('phpPageBuilder');
    }`

Thanks

**Comment by HansSchouten** [comment]
The class PHPageBuilder is not within the Providers namespace. You should add the following import at the top of your AppServiceProvider: `use PHPageBuilder\PHPageBuilder;`.

**Comment by macgadger** [comment]
> The class PHPageBuilder is not part of the `App\Providers` namespace. You should add the following import at the top of your AppServiceProvider: `use PHPageBuilder\PHPageBuilder;`.

Perfect! now i can access/views my pages i build in PageBuilder. But i am still unable to resolve page builder on custom routes as you guided in #8 . 

I have already logged with user using Auth, But while trying to open this URL `http://localhost:8000/admin/pages/1/build`
i am still getting `Authentication is disabled, use handlePublicRequest() and handleAuthenticatedRequest()`

Can you please provide me code how can i solve this.

Thanks!

**Comment by HansSchouten** [comment]
This means you have disabled the authentication module and thus cannot call the `handleRequest()` method, as this method does not have a way to check whether the user has been authenticated. You need two endpoints, a public controller action that calls `handlePublicRequest()` and a controller method that checks whether the user has been authenticated and then calls `handleAuthenticatedRequest()`.
