### ISSUE TITLE
Always Returning Error Authentication is disabled, use handlePublicRequest() and handleAuthenticatedRequest()

### ISSUE THREAD

**Issue by adityawiguna12** [HansSchouten/Laravel-Pagebuilder#63]
why when i follow your step on issue #8 , i always got error Authentication is disabled, use handlePublicRequest() and handleAuthenticatedRequest() , can you explain to me how to fix it ? i use laravel 6

**Comment by HansSchouten** [comment]
This warning means you are calling the `handleRequest()` while you are having login or the default website manager disabled [please have a look here](https://github.com/HansSchouten/PHPageBuilder/blob/master/src/PHPageBuilder.php#L258). In that case you should not call this method, but manually call the two methods it suggests.

Probably you are calling the `handleRequest()` method somewhere yourself? Or if you don't know how it is called, please add `debug_print_backtrace();` to the start of the `handleRequest()` method and look what is happening.

**Comment by HansSchouten** [comment]
I see there was an issue in which the `handleRequest()` was always called by this package, even with the website manager disabled. This has just been fixed, please update your installation.
