### ISSUE TITLE
Builder Blank White

### ISSUE THREAD

**Issue by adityawiguna12** [HansSchouten/Laravel-Pagebuilder#64]
Hello, after you fix #63 issue , now i found new issue , the builder always returning blank page, the code i use for custom controller is #8 and i still use laravel 6

**Comment by hilmiraditya** [comment]
same here

**Comment by yusufbachtiar** [comment]
someone has fixed this?

**Comment by HansSchouten** [comment]
There was an issue with the routes, I just pushed a commit to fix this.
