### ISSUE TITLE
Settings select box

### ISSUE THREAD

**Issue by billiemead** [HansSchouten/Laravel-Pagebuilder#65]
Hi,

I tried to follow  this for the expected format:

[https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/GrapesJS/Block/BlockAdapter.php#L136](url)

```
"settings" => [
    "nav-theme" => [
        "type" => "select",
        "label" => "Nav Theme",
        "name" => "navtheme",
        "options" => [
            'id' => 0, "name" => "nav-light",
            'id' => 1, "name" => "nav-dark",
        ]
    ],
]
```
But am getting an error so I must have it wrong?

And how do I use a .jpg file for thumbnail preview please???

**Comment by HansSchouten** [comment]
Instead of using a custom image that you should create and keep up-to-date, I would suggest to [render them automatically](https://github.com/HansSchouten/PHPageBuilder-Laravel-Screenshots).

What is the error you are getting? This looks correct to me.
