### ISSUE TITLE
Can Add New Language ?

### ISSUE THREAD

**Issue by adityawiguna12** [HansSchouten/Laravel-Pagebuilder#66]
Hello , can i add new language data ? if i can , how can i add new language

**Comment by HansSchouten** [comment]
Hi, yes you can change the languages. In [this folder](https://github.com/HansSchouten/PHPageBuilder/tree/master/lang) you can add a new language for the pagebuilder. Next you should change [this line](https://github.com/HansSchouten/PHPageBuilder/blob/master/config/config.example.php#L14) of your config. However, at the moment it is not yet possible to point to a new language file in a custom folder. It should be changed within the folder structure of the original source code.
