### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by dovanirjr** [HansSchouten/Laravel-Pagebuilder#67]
I don't run migration in the project Laravel with Laravel-Pagebuilder

The command **php artisan migrate** return this error:
**SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `pagebuilder__pages` add unique `pagebuilder__pages_route_unique`(`route`))**

My project AppServiceProvider.php is customized with:
`use Illuminate\Support\Facades\Schema;
public function boot()
    {
        Schema::defaultStringLength(191);
    }`

But the error persist.

**Comment by dovanirjr** [comment]
I solved this with 'engine' => 'InnoDB',
in to the file config/database.php
Database connections MYSQL'

**Comment by nomentsoa-andrianjatovo** [comment]
@HansSchouten I have `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testdb.pagebuilder__settings' doesn't exist` when migrating on installation. Do you know how to fix that?
