### ISSUE TITLE
error in updating, Installation and removal for reinstallation purpose

### ISSUE THREAD

**Issue by josh-whit-me** [HansSchouten/Laravel-Pagebuilder#68]
I installed the Laravel-Pagebuilder but I could not make use of it, when I tried to reinstall it using this 
          
          composer require hansschouten/phpagebuilder 

it gave me this error

          Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar://file_directory/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

so I had to prepend the following to it

          COMPOSER_MEMORY_LIMIT=-1

And this produces the following error 

             Your requirements could not be resolved to an installable set of packages.

            Problem 1
              - The requested package hansschouten/phpagebuilder (locked at v0.13.0, required as ^0.18.0) is satisfiable by hansschouten/phpagebuilder[v0.13.0] but these conflict with your requirements or minimum-stability

When I treid to remove the package, it gave me the following error

             Your requirements could not be resolved to an installable set of packages.

            Problem 1
              - The requested package hansschouten/phpagebuilder (locked at v0.13.0, required as ^0.18.0) is satisfiable by hansschouten/phpagebuilder[v0.13.0] but these conflict with your requirements or minimum-stability

I know I am using laravel 8 but when I tried to find the version of laravel I am using it gave me the following

	 php artisan -V

	   TypeError

	  Argument 1 passed to PHPageBuilder\PHPageBuilder::__construct() must be of the
	 type array, null given, called in installation_directory\vendor\hansschouten\laravel-pagebuilder\src\ServiceProvider.php on line 43

	  at installation_directory\vendor\hansschouten\phpagebuild
	er\src\PHPageBuilder.php:47
		 43      * PHPageBuilder constructor.
		 44      *
		 45      * @param array $config         configuration in the format defined in config/config.example.php
		 46      */
	     47     public function __construct(array $config)
		 48     {
		 49         if (session_status() === PHP_SESSION_NONE) {
		 50             session_start();
		 51         }
	           }

	  1   installation_directory\vendor\hansschouten\laravel-pagebuilder\src\ServiceProvider.php:43
		  PHPageBuilder\PHPageBuilder::__construct()

	  2   installation_directory\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
		  HansSchouten\LaravelPageBuilder\ServiceProvider::HansSchouten\LaravelPageBuilder\{closure}(Object(Illuminate\Foundation\Application), [])

Please I would appreciate prompt response, It is preventing me from doing any work

**Comment by HansSchouten** [comment]
You should run `composer update` to allow updating your locked PHPageBuilder v0.13.0 to be upgraded to the latest version.

**Comment by josh-whit-me** [comment]
Thanks for the reply. I had to completely remove the folder manually and reinstall it because it did not even allow me to remove not update it.

**Comment by HansSchouten** [comment]
There were some issues regarding this error in previous versions, so I guess there is no other way to fix it than completely remove the old version (lock file and vendor folder) and install the latest version. Bare in mind that this is a rough 0.x version that is not meant to be a completely stable project yet. I actually don't use this project myself at the moment, instead I use the core [PHPageBuilder](https://github.com/HansSchouten/PHPageBuilder) directly. I don't have more time to spend on this atm, as the pagebuilder is only a small fraction of what I am trying to accomplish. Feel free to help out if you have some time.
