### ISSUE TITLE
PHPageBuilder page not found. Check your URL: http://localhost/:8000/admin

### ISSUE THREAD

**Issue by glenn13** [HansSchouten/Laravel-Pagebuilder#69]
I used to follow this step:

Follow these steps to install Laravel Pagebuilder in your project:

```COMPOSER
composer require hansschouten/laravel-pagebuilder
```
```ARTISAN
php artisan vendor:publish --provider="HansSchouten\LaravelPageBuilder\ServiceProvider" --tag=config
```
Update the configuration in config/pagebuilder.php
```MIGRATION
php artisan migrate
```
Next, you need to create a theme:

```CREATE THEME
php artisan pagebuilder:create-theme [name here]
```
.. or publish the demo theme:

```PUBLISH
php artisan pagebuilder:publish-demo
```
Now you are able to login via /admin with admin and changethispassword (the admin URL and credentials can be changed in the pagebuilder config file).

After the installation, when i try to run the url based on config/pagebuilder.php it returns 

```Error
PHPageBuilder page not found. Check your URL: http://localhost/:8000/admin
```

**Comment by codegeek1001** [comment]
Do you have a typo in your APP_URL env ? You have listed the URL as http://localhost/:8080 (notice the / before colon : sign).

**Comment by glenn13** [comment]
it works now.. I just misconfigured the env file.. thanks
