### ISSUE TITLE
Getting a Page not found

### ISSUE THREAD

**Issue by williamengbjerg** [HansSchouten/Laravel-Pagebuilder#7]
I followed the instructions - installed on a new laravel project. But I keep getting a "Page not found" when trying to enter /admin page.

Also edited the pagebuilder.php - I'm I missing someting?:/

**Comment by HansSchouten** [comment]
The steps in the readme should be sufficient. Are you using the latest release? It should work even without editing the config file. Are you accessing /admin via a sub directory or is it installed in the root directory of your domain?

**Comment by williamengbjerg** [comment]
@HansSchouten - Thanks for reply. I've been following the steps up to several times:/ I don't see any existing admin in the folders or routes. When using Laravel I just get a blank page on the main page and the Error when typing /admin. I've installed laravel/ui with vue. Could that have any effects integrating with the pagebuilder?

**Comment by HansSchouten** [comment]
Could you check if you manage to get it working in a clean Laravel installation to see whether the laravel/ui and vue is the issue? I do not have an environment where I use it with the packages you mention.

**Comment by williamengbjerg** [comment]
@HansSchouten Just installed a clean laravel installation and followed the laravel-pagebuilder guide. Got the blank page again. Is it required to also follow the [Pagebuilder steps](https://github.com/HansSchouten/PHPageBuilder)?  

![Screenshot_1](https://user-images.githubusercontent.com/54719/80863321-b42dfc00-8c7b-11ea-95f4-d930f0bfb022.png)

**Comment by HansSchouten** [comment]
Strange, I just added it to a clean Laravel installation and everything works fine (PHP 7.3.7). I only followed the instructions in the [readme](https://github.com/HansSchouten/Laravel-Pagebuilder). 

I see you are testing in a Windows environment, so maybe there is an issue with paths. Could you go to `vendor/hansschouten/phpagebuilder/src/Core/helpers.php` and print the outputs of the calls to `phpb_in_module()` and `phpb_on_url()`?

**Comment by williamengbjerg** [comment]
Strange. I can try to run the install on my mac tomorrow. All tho I Mainly use my PC.

Output on /admin - phpb_on_url() seems to be empty:  
![image](https://user-images.githubusercontent.com/54719/80893097-95595500-8ccf-11ea-9bdc-99b5869f89c4.png)

**Comment by HansSchouten** [comment]
Ok, so the `$currentUrl` here should not have been `/`, but `/admin`. Then it would have matched with the website manager module's URL and have shown you the admin area.

Since `$currentUrl` is incorrect, the issue would be in the definition of `phpb_current_url()`. Could you check those values? I guess something is wrong with extraing the `$baseDirectory` in `phpb_current_url()`.

**Comment by williamengbjerg** [comment]
Yup. Is this the correct output? 

![image](https://user-images.githubusercontent.com/54719/80993083-c1ddb000-8e3a-11ea-9682-c9b2098fc359.png)

**Comment by AMB85** [comment]
I am not sure if my issue is related or not. I have a clean Laravel build but running on Linux. I can get to /admin but when you put in the credentials it goes to /admin/auth?action=login and I get no page found.

**Comment by HansSchouten** [comment]
So according to that output, `$baseDirectory` (PHP_SELF) does not contain the path relative to the domain you are trying to access, but instead it contains the entire local path. That is different from what I expected from the PHP docs:
![afbeelding](https://user-images.githubusercontent.com/5946444/81039822-4c112d00-8eaa-11ea-8b59-da8b12a85d70.png)
I will create a fix for it.

**Comment by williamengbjerg** [comment]
@HansSchouten Sounds good. I'll be ready to test it:)

**Comment by HansSchouten** [comment]
Thanks for your patience and helping to make this project better! I just made a new release which (among other fixes) does no longer rely on PHP_SELF. Could you try a new installation with v0.9.0?

**Comment by williamengbjerg** [comment]
@HansSchouten It works ! Looks pretty cool. I'm gonna test and try it:)

**Comment by HansSchouten** [comment]
Great! If you have any questions feel free to create a ticket, as the project is still in its early stages and documentation/demo content is far from perfect. FYI, you might encounter a loading issue if you are using Chrome by any chance. I am working on that.
