### ISSUE TITLE
Error in installing and configuring LaravelPageBuilder

### ISSUE THREAD

**Issue by josh-whit-me** [HansSchouten/Laravel-Pagebuilder#72]
I followed the instruction set in https://github.com/HansSchouten/Laravel-Pagebuilder

	step 1.	composer require hansschouten/laravel-pagebuilder

then
	
	step 2. php artisan vendor:publish --provider="HansSchouten\LaravelPageBuilder\ServiceProvider" --tag=config
	
But I have a question, how can I update or what am i supposed to update

	config/pagebuilder.php
inside pagebuilder.php there are areas I am confused about which are
	
	1. 'uploads_folder' => storage_path('app/pagebuilder/uploads') does not exist
	
	step 3. php artisan migrate

This gave me a lot of error

error 1. 

	SQLSTATE[HY000] [1049] Unknown database 'laravel' (SQL: select * from information_schema.tables where table_schema = laravel and table_name = migrations and table_type = 'BASE TABLE')
temporary way out
	It was not using the database which I have set inside the envirnment file, so in order to move forward I had to look for the file being used and change it 

error 2. After running migrate again

	 SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))
temporary way out
	 It was complaining about 2014_10_12_000000_create_users_table so I had to 
	 1. Add Schema::defaultStringLength(191); to  public function boot() and include use Illuminate\Support\Facades\Schema; in AppServiceProvider.php

error 3. After running migrate again

	Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `pages` add unique `pages_route_unique`(`route`))
temporary way out
	It was complaining about 2019_11_18_105032_create_pages_table so I had to remove 512 in route field
	
error 4. After running migrate again

	Illuminate\Database\QueryException
       SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `pages` add unique `pages_route_unique`(`route`))
temporary way out
	It was complaining about 2019_11_18_105615_create_uploads_table so I had to remove 512 in server_file field
	
finally  
	
	php artisan pagebuilder:publish-demo

Started the server went to http://localhost:8000/admin and still got the error in the web page
	
	Exception
	No PHPageBuilder config found, please run: php artisan vendor:publish --provider="HansSchouten\LaravelPageBuilder\ServiceProvider" --tag=config

I did this again in cmd 

	php artisan vendor:publish --provider="HansSchouten\LaravelPageBuilder\ServiceProvider" --tag=config
	
It still gave me the error above.

Please what i am supposed to do

**Comment by HansSchouten** [comment]
I guess it is related to your DB or Laravel installation. I have encountered [this before](https://laravel-news.com/laravel-5-4-key-too-long-error) but not in any project related to the pagebuilder. Once you fix the error the rest should work fine.
