### ISSUE TITLE
Greetings,

### ISSUE THREAD

**Issue by boudewijnbout** [HansSchouten/Laravel-Pagebuilder#77]
I just saw your project and I am really interested in trying it out for myself now.

However when im trying to apply it to my Laravel project I got this error?
<img width="1080" alt="Schermafbeelding 2021-01-13 om 21 19 59" src="https://user-images.githubusercontent.com/45170095/104506098-36313b80-55e5-11eb-929c-0418f10e1ebe.png">

I exactly followed your steps but I still got this error message. Hopefully you can help me out!

**Comment by HansSchouten** [comment]
Are you sure your .env file and the pagebuilder.php config files contain the right information? The pagebuilder.php config file should re-use your Laravel database credentials from the .env file.

**Comment by boudewijnbout** [comment]
Goodmorning, 

I double checked my credentials and it all seems correct, but maybe I am missing something? 

I added a screenshot of my .env file and my pagebuilder.php file.
<img width="1080" alt="Schermafbeelding 2021-01-14 om 09 28 09" src="https://user-images.githubusercontent.com/45170095/104564185-e5542e00-564a-11eb-96f1-60d941e73983.png">
<img width="1080" alt="Schermafbeelding 2021-01-14 om 09 26 44" src="https://user-images.githubusercontent.com/45170095/104564195-e8e7b500-564a-11eb-96c6-a6244d66f246.png">

**Comment by boudewijnbout** [comment]
Got it sorted out already.
