### ISSUE TITLE
PHPPageBuilder not found check your URL: http://localhost/:8080/admin

### ISSUE THREAD

**Issue by boudewijnbout** [HansSchouten/Laravel-Pagebuilder#78]
Goodafternoon,

I completed the installation and run my database migrations without any problem, unfortunately I got this error message now when trying to access the admin page of PHPPageBuilder: 

PHPPageBuilder not found check your URL: http://localhost/:8080/admin

I also added a screenshot of my .env file.

I already saw that someone has solved this problem before, but I don't understand how to implement that solution myself. So sorry for the duplication of this issue.

<img width="1080" alt="Schermafbeelding 2021-01-14 om 20 06 59" src="https://user-images.githubusercontent.com/45170095/104636713-114fcd80-56a4-11eb-8844-28b044b6043c.png">

**Comment by boudewijnbout** [comment]
Got it sorted out already.

**Comment by abdullahniazi96** [comment]
I am having the same issue can you please guide me on this.

**Comment by abdullahniazi96** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/85108041/124545368-5af2c700-de42-11eb-8763-58a6ae5d6e6b.png)
Here when I click on Get started.
this happens

![Screenshot (13)](https://user-images.githubusercontent.com/85108041/124545409-6ba33d00-de42-11eb-83a2-5661864d05d1.png)

**Comment by HansSchouten** [comment]
You changed your URL from localhost:8000 to localhost.
