### ISSUE TITLE
Categories not working

### ISSUE THREAD

**Issue by boudewijnbout** [HansSchouten/Laravel-Pagebuilder#79]
Goodafternoon

I am trying to give my blocks a category, however when I create the config.php in the block folder I want to give a category nothing is happening?

Greetings,

Boudewijn

**Comment by MagicianJona** [comment]
hey boudewijn i have the same problem

**Comment by HansSchouten** [comment]
Can you share the contents of your config file?

**Comment by boudewijnbout** [comment]
Goodafternoon,

These are the screenshots of my files you requested:

<img width="1173" alt="Schermafbeelding 2021-01-20 om 19 57 39" src="https://user-images.githubusercontent.com/45170095/105221756-da713000-5b59-11eb-992a-cf8ac07e6a9b.png">
<img width="1173" alt="Schermafbeelding 2021-01-20 om 19 57 32" src="https://user-images.githubusercontent.com/45170095/105221762-dcd38a00-5b59-11eb-9586-81ed95d7277a.png">

**Comment by HansSchouten** [comment]
A PHP file should start with `<?php`. That would solve the issue.

**Comment by boudewijnbout** [comment]
It's working. I am sorry this was a really dumb mistake..
