### ISSUE TITLE
Pagebuilder in a specific controller 

### ISSUE THREAD

**Issue by aledevil** [HansSchouten/Laravel-Pagebuilder#8]
good evening,
I have a project already started and running with Laravel 5.7.
I would like to give my users the possibility to create web pages through this page builder and therefore I would like to integrate this page builder into a specific controller of my project.

I tried to install it with the composer, but I can't edit the files to apply it only to a controller because they all files remain in the vendor folder and are not published in my project

**Comment by HansSchouten** [comment]
Hi, I would suggest you in the `pagebuilder.php` config file to set `use_login`, `use_website_manager` and `use_router` to false. Now the default PHPageBuilder login area and the frontend routes are disabled. Next you will need to implement your own controller actions for launching the pagebuilder and for serving all created pages. I am planning to make this easier and integrate it into the Laravel-Pagebuilder project, but at the moment this is what I used in another project:

## To manage pages
Create a basic table view that shows pages that are stored in a `pages` table in your database.

## To launch the pagebuilder

### Routes
```
Route::any('/admin/pages/{id}/build', 'App\Http\Controllers\PageBuilderController@build')->name('pagebuilder.build');
Route::any('/admin/pages/build', 'App\Http\Controllers\PageBuilderController@build');
```

### pagebuilder.php config
```
'pagebuilder' => [
	'class' => PHPageBuilder\Modules\GrapesJS\PageBuilder::class,
	'url' => '/admin/pages/build',      // the route you created for your pagebuilder controller
	'actions' => [
		'back' => '/admin/pages'    // URL to a table overview of all pages
	]
],
```

### AppServiceProvider boot method
```
// register singleton phppagebuilder (this ensures all phpb_ helpers have the right config without first manually creating a pagebuilder instance)
$this->app->singleton('phpPageBuilder', function($app) {
    return new PHPageBuilder(config('pagebuilder'));
});
$this->app->make('phpPageBuilder');
```

### Controller
```
/**
 * Edit the given page with the page builder.
 *
 * @param int|null $pageId
 * @throws Throwable
 */
public function build($pageId = null)
{
    $pageId = is_numeric($pageId) ? $pageId : ($_GET['page'] ?? null);
    $page = $this->page->find($pageId);
    $route = $_GET['route'] ?? null;
    $action = $_GET['action'] ?? null;

    $phpPageBuilder = app()->make('phpPageBuilder');
    $pageBuilder = $phpPageBuilder->getPageBuilder();

    $customScripts = view("website::pagebuilder.scripts")->render();
    $pageBuilder->customScripts('head', $customScripts);

    $pageBuilder->handleRequest($route, $action, $page);
}
```

## To publicly serve all pages

### Routes
Add this at the bottom of your `routes.php` file
```
Route::any('{uri}', [
    'uses' => 'App\Http\Controllers\WebsiteController@uri',
    'as' => 'page',
])->where('uri', '.*');
```

### Controller
```
/**
 * Show the website page with the given route.
 *
 * @param string $route
 */
public function uri($route = '/')
{
    $pageBuilder = app()->make('phpPageBuilder');
    $pageBuilder->handlePublicRequest();
}
```

**Comment by aledevil** [comment]
Hello there, thank you very much for your help
i've setup all page for index/create/delete my pages
i've setup the "edit" button that call your build function but i got always this error
 
**Error**
"Argument 3 passed to PHPageBuilder\Modules\GrapesJS\PageBuilder::handleRequest() must implement interface PHPageBuilder\Contracts\PageContract or be null, instance of App\PageBuilder given, called in C:\xampp\htdocs\crmhotel\app\Http\Controllers\PageBuilderController.php on line 166 "

**This my function build**
`    /**
     * Edit the given page with the page builder.
     *
     * @param int|null $pageId
     * @throws Throwable
     * @throws \Throwable
     */
   public function build($pageId = null)
    {
        $pageId = is_numeric($pageId) ? $pageId : ($_GET['page'] ?? null);
        $page = PageBuilder::find($pageId);
        $route = $_GET['route'] ?? null;
        $action = $_GET['action'] ?? null;

        $phpPageBuilder = app()->make('phpPageBuilder');
        $pageBuilder = $phpPageBuilder->getPageBuilder();

        $customScripts = view("pagebuilder.scripts")->render();
        $pageBuilder->customScripts('head', $customScripts);

        $pageBuilder->handleRequest($route, $action, $page);
    }
`
the variable $page call the method PageBuilder, it's correct? where i'm doing wrong?

**Comment by HansSchouten** [comment]
`$pageBuilder->handleRequest($route, $action, $page);` expects the `$page` argument to implement the `PHPageBuilder\Contracts\PageContract` to ensure all methods that the pagebuilder will call are present on the Page instance. So it should not be your created eloquent model, but a `PHPageBuilder\Page` instance (with the same id as your eloquent model instance would have). In the code I gave I did not explain where my `$page` came from, so I will update that in a minute to make my snippet complete. It tshould be:
```
$pageRepository = new \PHPageBuilder\Repositories\PageRepository;
$page = $pageRepository->findWithId($pageId);
```

**Comment by aledevil** [comment]
Ok perfetct! 
i add this function to my controller

`   
public function page($pageId = null) {
$pageRepository = new \PHPageBuilder\Repositories\PageRepository;
$page = $pageRepository->findWithId($pageId);
return $page;
}
`

now if i call the url "/pagebuilder/1/build" (1 is id of my page), i got the loader, but it keeps spinning forever

another question: 
when i create a new page, i add a row in db in table pagebuilder_pages with name and data, what i have to pass to "layout"? (using demo theme)
i have to add a row in pagebuilder_page_translations with page id, locale, title and route?
thank you again

**Comment by HansSchouten** [comment]
A layout is a default html structure in which all your page blocks will be loaded. The layouts are stored in the `themes\[theme-name]\layouts` folder. I added a default "master" layout which just includes the default html structure with all style and script tags. But you could also create for example a "header-footer" layout which also includes a header and footer by default to any of your pages that have this layout. So the layout field of a page should be the name of the folder in which you store your layout's `view.php` file.

You indeed need to also have a record in the `pagebuilder__page_translations` table, with the page id, the locale (probably `en`) and the route (which is the URL you access that page on in that language).

**Comment by aledevil** [comment]
now miss the assets 
i got an error in console log for "/assets/pagebuilder/page-injections.js:1"
with "Uncaught ReferenceError: $ is not defined" at Object.15 and Object.16

**Comment by HansSchouten** [comment]
I know that error and have [fixed it](https://github.com/HansSchouten/PHPageBuilder/commit/078f4773c543842bda3b99a0c9764951f93d42e0) in the PHPageBuilder project. For now can you try a different browser than Chrome or do an extra page reload if the error occurs? I will soon create a new release.

**Comment by aledevil** [comment]
the error of asset not found disappear, thank you

but got alway this
page-injection.js:1 
Uncaught ReferenceError: $ is not defined
    at Object.16 (page-injection.js:1)
    at e (page-injection.js:1)
    at Object.15 (page-injection.js:1)
    at e (page-injection.js:1)
    at page-injection.js:1
    at page-injection.js:1
and loading pagebuilder never stopped

**Comment by HansSchouten** [comment]
I just made a [v0.10.1 release](https://github.com/HansSchouten/PHPageBuilder/releases/tag/v0.10.1). Could try a `composer update` and see if the latest PHPageBuilder solves the issue.

**Comment by aledevil** [comment]
yep! now works!
thank you very much for your help

**Comment by HansSchouten** [comment]
Great! You're welcome

**Comment by aledevil** [comment]
this is not a issue, but a request

there is a way to include a plugin of grapejs?
for example if i want to include the plugin: gjs-preset-webpage
how i can do? i have to create all blocks?

**Comment by HansSchouten** [comment]
The way `grapesjs-blocks-basic` as part of `gjs-preset-webpage` is created it takes a very long time to create custom blocks (it is fully JS instead of just a piece of html in a file) and it is next to impossible to easily augment it with dynamic functionality (PHP that adds additional values and html structure), so therefore PHPageBuilder works completely different without any user supplied JS. Imagine you would be writing this for each of your blocks: https://github.com/artf/grapesjs-blocks-basic/blob/master/src/blocks.js. It takes a lot of effort to build it and to learn how the syntax works. As a result, unfortunately we cannot use the basic blocks of GrapesJS.

However, in this project each block has just a simple .html or a .php file and that's it. Creating blocks is now just a matter of tearing an awesome [HTML5 theme](https://themeforest.net/category/site-templates?sort=sales&tags=html5#content) apart into small snipets (i.e. blocks) and you're done.

That being said, I can imagine that is still not always pleasant for a new website so I am planning to create a default theme based on bootstrap that has blocks for each bootstrap component.

**Comment by aledevil** [comment]
> That being said, I can imagine that is still not always pleasant to do this for each new website so I am planning to create a default theme based on bootstrap that has blocks for each bootstrap component.

that would be really cool! if I can help you let me know
I'll start by creating theme that i need and then I'll show you if you want
thank you very much again for your help

**Comment by HansSchouten** [comment]
Awesome! It would be cool to have some example material somewhere, for others to quickly get started. The bootstrap theme is getting there, as well as better documentation, but at the moment I was still busy improving the system and build it while directly using it for some projects.

For reference, this is what I recently quickly build: https://www.gambiabirdingtours.com using [PHPageBuilder](https://github.com/HansSchouten/PHPageBuilder) (not even Laravel), based on [this theme](https://themeforest.net/item/greenforest-environmental-ecology-responsive-template/19671308). It was really just cutting up the template, create the pages with the desired blocks, add texts and done. I was thinking about sharing the code, but it uses a paid template so I guess I have to do just a bootstrap version in the near future.

**Comment by aledevil** [comment]
where i can edit the icon of blocks? 
![image](https://user-images.githubusercontent.com/35493810/81405659-64967700-9138-11ea-9788-4f7721a8dd36.png)

and there is a way to create another group like "General"?
thank you

**Comment by HansSchouten** [comment]
I use a cronjob to automatically take screenshots of the rendered blocks once a block has changed: https://github.com/HansSchouten/PHPageBuilder-Laravel-Screenshots. Each file contains the segment that should be added into your own project and you should run `composer require spatie/browsershot`.

To assign a block to another group, create a `config.php` in the folder of your block you can add the following:
```
<?php
return [
    'category' => 'Group name',
];
```

**Comment by aledevil** [comment]
i'm still tring to create some block, but some block created with view.html can't be edited in page builder
for example if i create a block "link" with insile view.html only the <a>some text</a> this have setting and can be edited in pagebuilder
but if i create a block input with label, the label can't be edit in pagebuilder

could you say why this? thank you

**Comment by HansSchouten** [comment]
That is correct, at the moment I did not create a sidebar settings for the input label attributes, but I did create [settings](https://github.com/HansSchouten/PHPageBuilder/blob/master/src/Modules/GrapesJS/resources/views/grapesjs/component-type-manager.php#L4) for a Link. So that explains this behaviour.

**Comment by aledevil** [comment]
i create a block like this
`` <div class="form-group"><label for="text">Label input</label><input type="text" class="form-control" id="text" name="text" placeholder="Placeholder" /></div>``

and the text "label input" is not editable

**Comment by HansSchouten** [comment]
Ah ok, that is an obvious bug, I will make it editable in the next release. About the placeholder I was already aware that it still had to be implemented.

**Comment by electroheadfx** [comment]
> https://www.gambiabirdingtours.com



> Awesome! It would be cool to have some example material somewhere, for others to quickly get started. The bootstrap theme is getting there, as well as better documentation, but at the moment I was still busy improving the system and build it while directly using it for some projects.
> 
> For reference, this is what I recently quickly build: https://www.gambiabirdingtours.com using [PHPageBuilder](https://github.com/HansSchouten/PHPageBuilder) and [the boilerplate](https://github.com/HansSchouten/PHPagebuilder-boilerplate) (not even Laravel), based on [this theme](https://themeforest.net/item/greenforest-environmental-ecology-responsive-template/19671308). It was really just cutting up the template, create the pages with the desired blocks, add texts, improve styling and done. I was thinking about sharing the code, but it uses a paid template so I guess I just have to do a bootstrap version in the near future.
> 
> What I can share already, is an example of the theme structure I used:
> ![afbeelding](https://user-images.githubusercontent.com/5946444/81400642-e339e700-912d-11ea-9426-d4d551792787.png)

Hey could you post an block example file with the preview file ?
would like awesome, thanks

**Comment by Andreidavid918** [comment]
@aledevil please let me know your discord/telegram/skype . I have some concerns about this issue.

**Comment by vladdivotek** [comment]
When I click the "View" button, a blank page opens. Please help
![Снимок экрана от 2021-12-10 12-54-01](https://user-images.githubusercontent.com/95685164/145563004-759f76dc-90c1-49d7-95ad-c8123873e12b.png)
![Снимок экрана от 2021-12-10 12-54-30](https://user-images.githubusercontent.com/95685164/145563017-3ce6cc92-ee77-4b76-b58e-fcfbab328f33.png)

.

**Comment by muneebahmad222** [comment]
Hi, 

I have updated the grapesjs version from 0.15.9 provided in the package to 0.17.27 by updating the CDN import as many grapesjs events are not available in the older version. But after updating it, I am getting an error in the app.js file which is in the public/assets/pagebuilder folder or in the dist folder of pagebuilder package for other functionalities like uploading an image or changing button text. This is the error I am getting "Uncaught TypeError: Cannot read properties of null (reading 'attributes')". The component gets removed so accessing its attribute property gives an error.
Is there any way to generate this file for the latest version of grapesjs or the proper way to update grapesjs version without breaking other things?
Your feedback in this regard will be highly appreciated.

**Comment by annus97** [comment]
Hi,

I have updated the grapesjs version from 0.15.9 provided in the package to 0.17.27 by updating the import of CDN in the package due to the unavailability of many events in older grapesjs version. After updating the version I am getting error in the app.js file which is in the public/assets/pagebuilder folder, the same file which is in the dist folder of phpagebuilder package. The error is "Uncaught TypeError: Cannot read properties of null (reading 'attributes')". It occurs in other basic functionalities like changing button text or uploading image. The component is removed so accessing its attribute property is giving the error.
Is there any way to generate this app.js file for the latest version of grapesjs or any other proper way to update grapesjs version? Your feedback in this regard will be highly appreciated.
