### ISSUE TITLE
CSS wont load 

### ISSUE THREAD

**Issue by MagicianJona** [HansSchouten/Laravel-Pagebuilder#80]
Dear Hans schouten,

I am trying to link the css as the demo does. However it’s not working for me unfortunately. I’m getting the following error message: [Resource interpreted as Stylesheet but transferred with MIME type text/html: "<URL>".]
![image](https://user-images.githubusercontent.com/45170122/105053917-bfc38c00-5a71-11eb-87e5-c0fb15e0da7b.png)
![image](https://user-images.githubusercontent.com/45170122/105054412-411b1e80-5a72-11eb-948b-4a77a3341fca.png)

Best regards,

Jonathan

**Comment by HansSchouten** [comment]
I think it is because of the port number in your URL that the `phpb_theme_asset` method is not recognizing the routes properly. If you inspect the responses of the URLs you show in the console screenshot it probably shows more details.

**Comment by MagicianJona** [comment]
Hi hans ive managed to fix it my pathing was wrong because of the PHPB_THEME_ASSET. But ive routed it correctly now thanks !!!
