### ISSUE TITLE
Getting only Header option in Pagebuilder page

### ISSUE THREAD

**Issue by chirag123456** [HansSchouten/Laravel-Pagebuilder#9]
i have run below commands
1) composer require hansschouten/laravel-pagebuilder
2) php artisan vendor:publish --provider="HansSchouten\LaravelPageBuilder\ServiceProvider" --tag=config
3) php artisan migrate
4) php artisan vendor:publish --provider="HansSchouten\LaravelPageBuilder\ServiceProvider" --tag=demo-theme

Now you are able to login via /admin with admin and changethispassword (the admin URL and credentials can be changed in the pagebuilder config file).

after that i have crated test page while i am click on Edit button from list i am redirecting to pagebuilder page after that some time only loader coming and some time it's working fine while it's working fine but i am getting only Header in Blocks -> General section -> Header (Only) comming nothing else please see atteched screenshot. so please guide me for resolve this issue. Thanks in advance

![Screenshot_2020-05-11_11-57-29](https://user-images.githubusercontent.com/16620982/81531687-cba66c80-9380-11ea-9074-230533e25df4.png)

**Comment by HansSchouten** [comment]
Hi, did you already create any blocks other than the header block? And can you ensure you have the latest release (v0.9.0), since the loading issue now should be fixed.

**Comment by chirag123456** [comment]
No i have not created any blocks yes i have updated composer in morning and loading issue is done in my system.

if there is any changes then can you pls guide me for same

Thanks
Chirag

**Comment by HansSchouten** [comment]
Good to hear that the loading issue is solved. Then all seems to work fine now, as I did not add any other blocks either. Currently this package is a tool to help building websites based on your own themes (for example by cutting up themes like [these](https://themeforest.net/category/site-templates?sort=sales&tags=html5#content). It does not yet come with many existing blocks, as I currently just needed a website builder that I can use for pro themes that I buy. And other people can use it in the same way I am doing now. However, in the future I will create a bootstrap demo theme.
