### ISSUE TITLE
Add Image Block With Open Image popup

### ISSUE THREAD

**Issue by milan-atulyam** [HansSchouten/Laravel-Pagebuilder#93]
Hi, Can you please suggest how to add image block with image popup 
like image block drag and drop in page builder and open image selection popup 
thank you.

![image](https://user-images.githubusercontent.com/78948340/112613853-97c42080-8e46-11eb-93ef-a0748febbf0c.png)
![image](https://user-images.githubusercontent.com/78948340/112613903-a6aad300-8e46-11eb-8bd8-def1c2724559.png)

**Comment by HansSchouten** [comment]
Hi you can add a new view.html block with a simple `<img>` html tag and a placeholder image. Next you can drag that block on your page and double click the image to change it.

**Comment by abdullahniazi96** [comment]
after doing this getting this error

file_get_contents(D:\Programming\xampp\htdocs\laravel-pagebuilder\themes/demo/blocks/img/view.html): failed to open stream: No such file or directory

**Comment by abdullahniazi96** [comment]
When I upload the image its not visible
